type_to_color = {'normal': 0xa5a5a7, 'feu': 0xd0361b, 'eau': 0x1b69d0, 'plante': 0x0a8017, 'electr': 0xf0f401, 'fée': 0xdf89e1, 'roche': 0x744b25, 'sol': 0xab5707, 'dragon': 0x26077e, 'acier': 0x545454, 'combat': 0xd65d00, 'psy': 0xa238b7, 'glace': 0x84eef0, 'vol': 0xb8e0e0, 'poison': 0x5e0080, 'insect': 0x6bb300, 'tenebr': 0x333333, 'spectr': 0x3c0f61}

type_to_emote = {'normal': "<:normal:1061297285587271680>", 'feu': "<:feu:1061296905260371978>", 'eau': '<:eau:1061297068230058074>', 'plante': '<:plante:1061297202967875634>', 'electr': '<:electr:1061298097516462120>', 'fee': '<:fee:1061297371163656223>', 'roche': '<:roche:1061296981147922552>', 'sol': '<:sol:1061296807893815346>', 'dragon': '<:dragon:1061297735086657616>', 'acier': "<:acier:1061297813062942903>", 'combat': '<:combat:1061297882503843941>', 'psy': '<:psy:1061297643449499769>', 'glace': '<:glace:1061298019833757766>', 'vol': '<:vol:1061298171587874856>', 'poison': '<:poison:1061298317415424040>', 'insect': '<:insect:1061297136190377994>', 'tenebr': '<:tenebr:1061297540215099404>', 'spectr': '<:spectr:1061297459059499008>'}

french_types = {'normal': 'normal', 'fire': 'feu', 'water': 'eau', 'grass': 'plante', 'electric': 'electr', 'fairy': 'fee', 'rock': 'roche', 'ground': 'sol', 'dragon': 'dragon', 'steel': 'acier', 'fighting': 'combat', 'psychic': 'psy', 'ice': 'glace', 'flying': 'vol', 'poison': 'poison', 'bug': 'insect', 'dark': 'tenebr', 'ghost': 'spectr'}

loca={     
     "Bulbizarre":"\n - Centre de Recherches,\n - Temple Forestier",
     "Herbizarre":"\n - Faire évoluer Bulbizarre",
     "Florizarre":"\n - Faire évoluer Herbizarre",
     "Salamèche":"\n - Centre de Recherches,\n - Temple du Désert",
     "Reptincel":"\n - Faire évoluer Salamèche",
     "Dracaufeu":"\n - Faire évoluer Reptincel",
     "Carapuce":"\n - Centre de Recherches",
     "Carabaffe":"\n - Faire évoluer Carapuce",
     "Tortank":"\n - Faire évoluer Carabaffe",
     "Chenipan":"\n- Bois Solidago",
     "Chrysacier":"\n - Faire évoluer Chenipan",
     "Papilusion":"\n - Faire évoluer Chrysacier",
     "Aspicot":"\n - Faire un œuf",
     "Coconfort":"\n- Bois Solidago",
     "Dardargnan":"\n- Bois Solidago",
     "Roucool":"*Localisation inconnue*",
     "Roucoups":"*Localisation inconnue*",
     "Roucarnage":"*Localisation inconnue*",
     "Rattata":"*Localisation inconnue*",
     "Rattatac":"*Localisation inconnue*",
     "Piafabec":"*Localisation inconnue*",
     "Rapasdepic":"*Localisation inconnue*",
     "Abo":"*Localisation inconnue*",
     "Arbok":"*Localisation inconnue*",
     "Pikachu":"\n- Centre de Recherches\n",
     "Raichu":"\n - Faire évoluer Pikachu",
     "Sabelette":"*Localisation inconnue*",
     "Sablaireau":"*Localisation inconnue*",
     "Nidoran♀":"*Localisation inconnue*",
     "Nidorina":"*Localisation inconnue*",
     "Nidoqueen":"*Localisation inconnue*",
     "Nidoran♂":"*Localisation inconnue*",
     "Nidorino":"*Localisation inconnue*",
     "Nidoking":"*Localisation inconnue*",
     "Mélofée":"*Localisation inconnue*",
     "Mélodelfe":"*Localisation inconnue*",
     "Goupix":"*Localisation inconnue*",
     "Feunard":"*Localisation inconnue*",
     "Rondoudou":"*Localisation inconnue*",
     "Grodoudou":"*Localisation inconnue*",
     "Nosferapti":"*Localisation inconnue*",
     "Nosferalto":"*Localisation inconnue*",
     "Mystherbe":"\n - Bois Solidago",
     "Ortide":"*Localisation inconnue*",
     "Rafflesia":"*Localisation inconnue*",
     "Paras":"\n - Bois Solidago",
     "Parasect":"\n - Bois Solidago",
     "Mimitoss":"\n - Bois Solidago",
     "Aéromite":"\n - Bois Solidago",
     "Taupiqueur":"*Localisation inconnue*",
     "Triopikeur":"*Localisation inconnue*",
     "Miaouss":"*Localisation inconnue*",
     "Persian":"*Localisation inconnue*",
     "Psykokwak":"*Localisation inconnue*",
     "Akwakwak":"*Localisation inconnue*",
     "Férosinge":"*Localisation inconnue*",
     "Colossinge":"*Localisation inconnue*",
     "Caninos":"*Localisation inconnue*",
     "Arcanin":"*Localisation inconnue*",
     "Ptitard":"*Localisation inconnue*",
     "Têtarte":"*Localisation inconnue*",
     "Tartard":"*Localisation inconnue*",
     "Abra":"*Localisation inconnue*",
     "Kadabra":"*Localisation inconnue*",
     "Alakazam":"*Localisation inconnue*",
     "Machoc":"*Localisation inconnue*",
     "Machopeur":"*Localisation inconnue*",
     "Mackogneur":"*Localisation inconnue*",
     "Chétiflor":"*Localisation inconnue*",
     "Boustiflor":"*Localisation inconnue*",
     "Empiflor":"*Localisation inconnue*",
     "Tentacool":"*Localisation inconnue*",
     "Tentacruel":"*Localisation inconnue*",
     "Racaillou":"*Localisation inconnue*",
     "Gravalanch":"*Localisation inconnue*",
     "Grolem":"*Localisation inconnue*",
     "Ponyta":"*Localisation inconnue*",
     "Galopa":"*Localisation inconnue*",
     "Ramoloss":"*Localisation inconnue*",
     "Flagadoss":"*Localisation inconnue*",
     "Magnéti":"*Localisation inconnue*",
     "Magnéton":"*Localisation inconnue*",
     "Canarticho":"*Localisation inconnue*",
     "Doduo":"*Localisation inconnue*",
     "Dodrio":"*Localisation inconnue*",
     "Otaria":"*Localisation inconnue*",
     "Lamantine":"*Localisation inconnue*",
     "Tadmorv":"*Localisation inconnue*",
     "Grotadmorv":"*Localisation inconnue*",
     "Kokiyas":"*Localisation inconnue*",
     "Crustabri":"*Localisation inconnue*",
     "Fantominus":"\n - Bois Solidago",
     "Spectrum":"\n - Bois Solidago",
     "Ectoplasma":"\n - Faire évoluer Spectrum",
     "Onix":"*Localisation inconnue*",
     "Soporifik":"\n - Bois Solidago",
     "Hypnomade":"Faire évoluer Soporifik",
     "Krabby":"*Localisation inconnue*",
     "Krabboss":"*Localisation inconnue*",
     "Voltorbe":"*Localisation inconnue*",
     "Électrode":"*Localisation inconnue*",
     "Noeunoeuf":"*Localisation inconnue*",
     "Noadkoko":"*Localisation inconnue*",
     "Osselait":"*Localisation inconnue*",
     "Ossatueur":"*Localisation inconnue*",
     "Kicklee":"*Localisation inconnue*",
     "Tygnon":"*Localisation inconnue*",
     "Excelangue":"*Localisation inconnue*",
     "Smogo":"*Localisation inconnue*",
     "Smogogo":"*Localisation inconnue*",
     "Rhinocorne":"*Localisation inconnue*",
     "Rhinoféros":"*Localisation inconnue*",
     "Leveinard":"\n - Bois Solidago",
     "Saquedeneu":"*Localisation inconnue*",
     "Kangourex":"*Localisation inconnue*",
     "Hypotrempe":"*Localisation inconnue*",
     "Hypocéan":"*Localisation inconnue*",
     "Poissirène":"*Localisation inconnue*",
     "Poissoroy":"*Localisation inconnue*",
     "Stari":"*Localisation inconnue*",
     "Staross":"*Localisation inconnue*",
     "M. Mime":"*Localisation inconnue*",
     "Insécateur":"*Localisation inconnue*",
     "Lippoutou":"*Localisation inconnue*",
     "Élektek":"*Localisation inconnue*",
     "Magmar":"*Localisation inconnue*",
     "Scarabrute":"\n - Bois Solidago\n",
     "Tauros":"*Localisation inconnue*",
     "Magicarpe":"*Localisation inconnue*",
     "Léviator":"*Localisation inconnue*",
     "Lokhlass":"*Localisation inconnue*",
     "Métamorph":"*Localisation inconnue*",
     "Évoli":"*Localisation inconnue*",
     "Aquali":"*Localisation inconnue*",
     "Voltali":"*Localisation inconnue*",
     "Pyroli":"*Localisation inconnue*",
     "Porygon":"*Localisation inconnue*",
     "Amonita":"*Localisation inconnue*",
     "Amonistar":"*Localisation inconnue*",
     "Kabuto":"*Localisation inconnue*",
     "Kabutops":"*Localisation inconnue*",
     "Ptéra":"*Localisation inconnue*",
     "Ronflex":"*Localisation inconnue*",
     "Artikodin":"*Localisation inconnue*",
     "Électhor":"*Localisation inconnue*",
     "Sulfura":"*Localisation inconnue*",
     "Minidraco":"*Localisation inconnue*",
     "Draco":"*Localisation inconnue*",
     "Dracolosse":"*Localisation inconnue*",
     "Mewtwo":"*Localisation inconnue*",
     "Mew":"*Localisation inconnue*",
     "Germignon":"\n - Centre de Recherches",
     "Macronium":"\n - Faire évoluer Germignon",
     "Méganium":"\n - Faire évoluer Macronium",
     "Héricendre":"\n - Centre de Recherches",
     "Feurisson":"\n - Faire évoluer Héricendre",
     "Typhlosion":"\n - Faire évoluer Feurisson",
     "Kaiminus":"\n - Centre de Recherches",
     "Crocrodil":"\n - Faire évoluer Kaiminus",
     "Aligatueur":"\n - Faire évoluer Crocrodil",
     "Fouinette":"*Localisation inconnue*",
     "Fouinar":"*Localisation inconnue*",
     "Hoothoot":"*Localisation inconnue*",
     "Noarfang":"*Localisation inconnue*",
     "Coxy":"\n - Bois Solidago",
     "Coxyclaque":"\n - Bois Solidago",
     "Mimigal":"\n - Bois Solidago",
     "Migalos":"\n - Bois Solidago",
     "Nostenfer":"*Localisation inconnue*",
     "Loupio":"*Localisation inconnue*",
     "Lanturn":"*Localisation inconnue*",
     "Pichu":"*Localisation inconnue*",
     "Mélo":"*Localisation inconnue*",
     "Toudoudou":"*Localisation inconnue*",
     "Togepi":"*Localisation inconnue*",
     "Togetic":"*Localisation inconnue*",
     "Natu":"*Localisation inconnue*",
     "Xatu":"*Localisation inconnue*",
     "Wattouat":"*Localisation inconnue*",
     "Lainergie":"*Localisation inconnue*",
     "Pharamp":"*Localisation inconnue*",
     "Joliflor":"*Localisation inconnue*",
     "Marill":"*Localisation inconnue*",
     "Azumarill":"*Localisation inconnue*",
     "Simularbre":"*Localisation inconnue*",
     "Tarpaud":"*Localisation inconnue*",
     "Granivol":"*Localisation inconnue*",
     "Floravol":"*Localisation inconnue*",
     "Cotovol":"*Localisation inconnue*",
     "Capumain":"*Localisation inconnue*",
     "Tournegrin":"*Localisation inconnue*",
     "Héliatronc":"*Localisation inconnue*",
     "Yanma":"*Localisation inconnue*",
     "Axoloto":"*Localisation inconnue*",
     "Maraiste":"*Localisation inconnue*",
     "Mentali":"*Localisation inconnue*",
     "Noctali":"*Localisation inconnue*",
     "Cornèbre":"*Localisation inconnue*",
     "Roigada":"*Localisation inconnue*",
     "Feuforêve":"*Localisation inconnue*",
     "Zarbi":"*Localisation inconnue*",
     "Qulbutoké":"*Localisation inconnue*",
     "Girafarig":"*Localisation inconnue*",
     "Pomdepik":"*Localisation inconnue*",
     "Foretress":"*Localisation inconnue*",
     "Insolourdo":"*Localisation inconnue*",
     "Scorplane":"*Localisation inconnue*",
     "Steelix":"*Localisation inconnue*",
     "Snubbull":"*Localisation inconnue*",
     "Granbull":"*Localisation inconnue*",
     "Qwilfish":"*Localisation inconnue*",
     "Cizayox":"- Bois Solidago",
     "Caratroc":"\n - Bois Solidago",
     "Scarhino":"\n - Bois Solidago",
     "Farfuret":"*Localisation inconnue*",
     "Teddiursa":"*Localisation inconnue*",
     "Ursaring":"*Localisation inconnue*",
     "Limagma":"*Localisation inconnue*",
     "Volcaropod":"*Localisation inconnue*",
     "Marcacrin":"*Localisation inconnue*",
     "Cochignon":"*Localisation inconnue*",
     "Corayon":"*Localisation inconnue*",
     "Rémoraid":"*Localisation inconnue*",
     "Octillery":"*Localisation inconnue*",
     "Cadoizo":"*Localisation inconnue*",
     "Démanta":"*Localisation inconnue*",
     "Airmure":"*Localisation inconnue*",
     "Malosse":"*Localisation inconnue*",
     "Démolosse":"*Localisation inconnue*",
     "Hyporoi":"*Localisation inconnue*",
     "Phanpy":"*Localisation inconnue*",
     "Donphan":"*Localisation inconnue*",
     "Porygon2":"*Localisation inconnue*",
     "Cerfrousse":"*Localisation inconnue*",
     "Queulorior":"*Localisation inconnue*",
     "Debugant":"*Localisation inconnue*",
     "Kapoera":"*Localisation inconnue*",
     "Lippouti":"*Localisation inconnue*",
     "Élekid":"*Localisation inconnue*",
     "Magby":"*Localisation inconnue*",
     "Écrémeuh":"*Localisation inconnue*",
     "Leuphorie":"*Localisation inconnue*",
     "Raikou":"*Localisation inconnue*",
     "Entei":"*Localisation inconnue*",
     "Suicune":"*Localisation inconnue*",
     "Embrylex":"*Localisation inconnue*",
     "Ymphect":"*Localisation inconnue*",
     "Tyranocif":"*Localisation inconnue*",
     "Lugia":"*Localisation inconnue*",
     "Ho-Oh":"*Localisation inconnue*",
     "Celebi":"*Localisation inconnue*",
     "Arcko":"- Centre de Recherches",
     "Massko":"- Faire évoluer Arcko",
     "Jungko":"- Faire évoluer Massko",
     "Poussifeu":"\n - Centre de Recherches",
     "Galifeu":"\n - Faire évoluer Poussifeu",
     "Braségali":"\n - Faire évoluer Galifeu",
     "Gobou":"\n - Centre de Recherches",
     "Flobio":"\n - Faire évoluer Gobou",
     "Laggron":"\n - Faire évoluer Flobio",
     "Medhyèna":"*Localisation inconnue*",
     "Grahyèna":"*Localisation inconnue*",
     "Zigzaton":"*Localisation inconnue*",
     "Linéon":"*Localisation inconnue*",
     "Chenipotte":"*Localisation inconnue*",
     "Armulys":"*Localisation inconnue*",
     "Charmillon":"*Localisation inconnue*",
     "Blindalys":"*Localisation inconnue*",
     "Papinox":"*Localisation inconnue*",
     "Nénupiot":"*Localisation inconnue*",
     "Lombre":"*Localisation inconnue*",
     "Ludicolo":"*Localisation inconnue*",
     "Grainipiot":"*Localisation inconnue*",
     "Pifeuil":"*Localisation inconnue*",
     "Tengalice":"*Localisation inconnue*",
     "Nirondelle":"*Localisation inconnue*",
     "Hélédelle":"*Localisation inconnue*",
     "Goélise":"*Localisation inconnue*",
     "Bekipan":"*Localisation inconnue*",
     "Tarsal":"*Localisation inconnue*",
     "Kirlia":"*Localisation inconnue*",
     "Gardevoir":"*Localisation inconnue*",
     "Arakdo":"*Localisation inconnue*",
     "Maskadra":"*Localisation inconnue*",
     "Balignon":"*Localisation inconnue*",
     "Chapignon":"*Localisation inconnue*",
     "Parecool":"*Localisation inconnue*",
     "Vigoroth":"*Localisation inconnue*",
     "Monaflèmit":"*Localisation inconnue*",
     "Ningale":"*Localisation inconnue*",
     "Ninjask":"*Localisation inconnue*",
     "Munja":"*Localisation inconnue*",
     "Chuchmur":"*Localisation inconnue*",
     "Ramboum":"*Localisation inconnue*",
     "Brouhabam":"*Localisation inconnue*",
     "Makuhita":"*Localisation inconnue*",
     "Hariyama":"*Localisation inconnue*",
     "Azurill":"*Localisation inconnue*",
     "Tarinor":"*Localisation inconnue*",
     "Skitty":"*Localisation inconnue*",
     "Delcatty":"*Localisation inconnue*",
     "Ténéfix":"*Localisation inconnue*",
     "Mysdibule":"*Localisation inconnue*",
     "Galekid":"*Localisation inconnue*",
     "Galegon":"*Localisation inconnue*",
     "Galeking":"*Localisation inconnue*",
     "Méditikka":"*Localisation inconnue*",
     "Charmina":"*Localisation inconnue*",
     "Dynavolt":"*Localisation inconnue*",
     "Élecsprint":"*Localisation inconnue*",
     "Posipi":"*Localisation inconnue*",
     "Négapi":"*Localisation inconnue*",
     "Muciole":"*Localisation inconnue*",
     "Lumivole":"*Localisation inconnue*",
     "Rosélia":"*Localisation inconnue*",
     "Gloupti":"*Localisation inconnue*",
     "Avaltout":"*Localisation inconnue*",
     "Carvanha":"*Localisation inconnue*",
     "Sharpedo":"*Localisation inconnue*",
     "Wailmer":"*Localisation inconnue*",
     "Wailord":"*Localisation inconnue*",
     "Chamallot":"*Localisation inconnue*",
     "Camérupt":"*Localisation inconnue*",
     "Chartor":"*Localisation inconnue*",
     "Spoink":"*Localisation inconnue*",
     "Groret":"*Localisation inconnue*",
     "Spinda":"*Localisation inconnue*",
     "Kraknoix":"*Localisation inconnue*",
     "Vibraninf":"*Localisation inconnue*",
     "Libégon":"*Localisation inconnue*",
     "Cacnea":"*Localisation inconnue*",
     "Cacturne":"*Localisation inconnue*",
     "Tylton":"*Localisation inconnue*",
     "Altaria":"*Localisation inconnue*",
     "Mangriff":"*Localisation inconnue*",
     "Séviper":"*Localisation inconnue*",
     "Séléroc":"*Localisation inconnue*",
     "Solaroc":"*Localisation inconnue*",
     "Barloche":"*Localisation inconnue*",
     "Barbicha":"*Localisation inconnue*",
     "Écrapince":"*Localisation inconnue*",
     "Colhomard":"*Localisation inconnue*",
     "Balbuto":"*Localisation inconnue*",
     "Kaorine":"*Localisation inconnue*",
     "Lilia":"*Localisation inconnue*",
     "Vacilys":"*Localisation inconnue*",
     "Anorith":"*Localisation inconnue*",
     "Armaldo":"*Localisation inconnue*",
     "Barpau":"*Localisation inconnue*",
     "Milobellus":"*Localisation inconnue*",
     "Morphéo":"*Localisation inconnue*",
     "Kecleon":"*Localisation inconnue*",
     "Polichombr":"*Localisation inconnue*",
     "Branette":"*Localisation inconnue*",
     "Skelénox":"*Localisation inconnue*",
     "Téraclope":"*Localisation inconnue*",
     "Tropius":"*Localisation inconnue*",
     "Éoko":"*Localisation inconnue*",
     "Absol":"*Localisation inconnue*",
     "Okéoké":"*Localisation inconnue*",
     "Stalgamin":"*Localisation inconnue*",
     "Oniglali":"*Localisation inconnue*",
     "Obalie":"*Localisation inconnue*",
     "Phogleur":"*Localisation inconnue*",
     "Kaimorse":"*Localisation inconnue*",
     "Coquiperl":"*Localisation inconnue*",
     "Serpang":"*Localisation inconnue*",
     "Rosabyss":"*Localisation inconnue*",
     "Relicanth":"*Localisation inconnue*",
     "Lovdisc":"*Localisation inconnue*",
     "Draby":"*Localisation inconnue*",
     "Drackhaus":"*Localisation inconnue*",
     "Drattak":"*Localisation inconnue*",
     "Terhal":"*Localisation inconnue*",
     "Métang":"*Localisation inconnue*",
     "Métalosse":"*Localisation inconnue*",
     "Regirock":"*Localisation inconnue*",
     "Regice":"*Localisation inconnue*",
     "Registeel":"*Localisation inconnue*",
     "Latias":"*Localisation inconnue*",
     "Latios":"*Localisation inconnue*",
     "Kyogre":"*Localisation inconnue*",
     "Groudon":"*Localisation inconnue*",
     "Rayquaza":"*Localisation inconnue*",
     "Jirachi":"*Localisation inconnue*",
     "Deoxys":"*Localisation inconnue*",
     "Tortipouss":"-\n Centre de Recherches",
     "Boskara":"\n- Faire évoluer Tortipouss",
     "Torterra":"\n- Faire évoluer Boskara",
     "Ouisticram":"\n- Centre de Recherches",
     "Chimpenfeu":"\nFaire évoluer Ouisticram",
     "Simiabraz":"\nFaire évoluer Simiabraz",
     "Tiplouf":"\n- Centre de Recherches",
     "Prinplouf":"\n- Faire évoluer Tiplouf",
     "Pingoléon":"\n- Faire évoluer Prinplouf",
     "Étourmi":"*Localisation inconnue*",
     "Étourvol":"*Localisation inconnue*",
     "Étouraptor":"*Localisation inconnue*",
     "Keunotor":"*Localisation inconnue*",
     "Castorno":"*Localisation inconnue*",
     "Crikzik":"*Localisation inconnue*",
     "Mélokrik":"*Localisation inconnue*",
     "Lixy":"*Localisation inconnue*",
     "Luxio":"*Localisation inconnue*",
     "Luxray":"*Localisation inconnue*",
     "Rozbouton":"*Localisation inconnue*",
     "Roserade":"*Localisation inconnue*",
     "Kranidos":"*Localisation inconnue*",
     "Charkos":"*Localisation inconnue*",
     "Dinoclier":"*Localisation inconnue*",
     "Bastiodon":"*Localisation inconnue*",
     "Cheniti":"*Localisation inconnue*",
     "Cheniselle":"*Localisation inconnue*",
     "Papilord":"*Localisation inconnue*",
     "Apitrini":"*Localisation inconnue*",
     "Apireine":"*Localisation inconnue*",
     "Pachirisu":"*Localisation inconnue*",
     "Mustébouée":"*Localisation inconnue*",
     "Mustéflott":"*Localisation inconnue*",
     "Ceribou":"*Localisation inconnue*",
     "Ceriflor":"*Localisation inconnue*",
     "Sancoki":"*Localisation inconnue*",
     "Tritosor":"*Localisation inconnue*",
     "Capidextre":"*Localisation inconnue*",
     "Baudrive":"*Localisation inconnue*",
     "Grodrive":"*Localisation inconnue*",
     "Laporeille":"*Localisation inconnue*",
     "Lockpin":"*Localisation inconnue*",
     "Magirêve":"*Localisation inconnue*",
     "Corboss":"*Localisation inconnue*",
     "Chaglam":"*Localisation inconnue*",
     "Chaffreux":"*Localisation inconnue*",
     "Korillon":"*Localisation inconnue*",
     "Moufouette":"*Localisation inconnue*",
     "Moufflair":"*Localisation inconnue*",
     "Archéomire":"*Localisation inconnue*",
     "Archéodong":"*Localisation inconnue*",
     "Manzaï":"*Localisation inconnue*",
     "Mime Jr.":"*Localisation inconnue*",
     "Ptiravi":"*Localisation inconnue*",
     "Pijako":"*Localisation inconnue*",
     "Spiritomb":"*Localisation inconnue*",
     "Griknot":"*Localisation inconnue*",
     "Carmache":"*Localisation inconnue*",
     "Carchacrok":"*Localisation inconnue*",
     "Goinfrex":"*Localisation inconnue*",
     "Riolu":"*Localisation inconnue*",
     "Lucario":"*Localisation inconnue*",
     "Hippopotas":"*Localisation inconnue*",
     "Hippodocus":"*Localisation inconnue*",
     "Rapion":"*Localisation inconnue*",
     "Drascore":"*Localisation inconnue*",
     "Cradopaud":"*Localisation inconnue*",
     "Coatox":"*Localisation inconnue*",
     "Vortente":"*Localisation inconnue*",
     "Écayon":"*Localisation inconnue*",
     "Luminéon":"*Localisation inconnue*",
     "Babimanta":"*Localisation inconnue*",
     "Blizzi":"*Localisation inconnue*",
     "Blizzaroi":"*Localisation inconnue*",
     "Dimoret":"*Localisation inconnue*",
     "Magnézone":"*Localisation inconnue*",
     "Coudlangue":"*Localisation inconnue*",
     "Rhinastoc":"*Localisation inconnue*",
     "Bouldeneu":"*Localisation inconnue*",
     "Élekable":"*Localisation inconnue*",
     "Maganon":"*Localisation inconnue*",
     "Togekiss":"*Localisation inconnue*",
     "Yanmega":"*Localisation inconnue*",
     "Phyllali":"*Localisation inconnue*",
     "Givrali":"*Localisation inconnue*",
     "Scorvol":"*Localisation inconnue*",
     "Mammochon":"*Localisation inconnue*",
     "Porygon-Z":"*Localisation inconnue*",
     "Gallame":"*Localisation inconnue*",
     "Tarinorme":"*Localisation inconnue*",
     "Noctunoir":"*Localisation inconnue*",
     "Momartik":"*Localisation inconnue*",
     "Motisma":"*Localisation inconnue*",
     "Créhelf":"*Localisation inconnue*",
     "Créfollet":"*Localisation inconnue*",
     "Créfadet":"*Localisation inconnue*",
     "Dialga":"*Localisation inconnue*",
     "Palkia":"*Localisation inconnue*",
     "Heatran":"*Localisation inconnue*",
     "Regigigas":"*Localisation inconnue*",
     "Giratina":"*Localisation inconnue*",
     "Cresselia":"*Localisation inconnue*",
     "Phione":"*Localisation inconnue*",
     "Manaphy":"*Localisation inconnue*",
     "Darkrai":"*Localisation inconnue*",
     "Shaymin":"*Localisation inconnue*",
     "Arceus":"*Localisation inconnue*",
     "Victini":"*Localisation inconnue*",
     "Vipélierre":"\n- Centre de Recherches",
     "Lianaja":"\n- Faire évoluer Vipélierre",
     "Majaspic":"\n- Faire évoluer Lianaja",
     "Gruikui":"\n- Centre de Recherches",
     "Grotichon":"\n- Faire évoluer Gruikui",
     "Roitiflam":"\n- Faire évoluer Grotichon",
     "Moustillon":"\n- Centre de Recherches",
     "Mateloutre":"\n- Faire évoluer Moustillon",
     "Clamiral":"\n- Faire évoluer Mateloutre",
     "Ratentif":"*Localisation inconnue*",
     "Miradar":"*Localisation inconnue*",
     "Ponchiot":"*Localisation inconnue*",
     "Ponchien":"*Localisation inconnue*",
     "Mastouffe":"*Localisation inconnue*",
     "Chacripan":"*Localisation inconnue*",
     "Léopardus":"*Localisation inconnue*",
     "Feuillajou":"*Localisation inconnue*",
     "Feuiloutan":"*Localisation inconnue*",
     "Flamajou":"*Localisation inconnue*",
     "Flamoutan":"*Localisation inconnue*",
     "Flotajou":"*Localisation inconnue*",
     "Flotoutan":"*Localisation inconnue*",
     "Munna":"*Localisation inconnue*",
     "Mushana":"*Localisation inconnue*",
     "Poichigeon":"*Localisation inconnue*",
     "Colombeau":"*Localisation inconnue*",
     "Déflaisan":"*Localisation inconnue*",
     "Zébibron":"*Localisation inconnue*",
     "Zéblitz":"*Localisation inconnue*",
     "Nodulithe":"*Localisation inconnue*",
     "Géolithe":"*Localisation inconnue*",
     "Gigalithe":"*Localisation inconnue*",
     "Chovsourir":"*Localisation inconnue*",
     "Rhinolove":"*Localisation inconnue*",
     "Rototaupe":"*Localisation inconnue*",
     "Minotaupe":"*Localisation inconnue*",
     "Nanméouïe":"*Localisation inconnue*",
     "Charpenti":"*Localisation inconnue*",
     "Ouvrifier":"*Localisation inconnue*",
     "Bétochef":"*Localisation inconnue*",
     "Tritonde":"*Localisation inconnue*",
     "Batracné":"*Localisation inconnue*",
     "Crapustule":"*Localisation inconnue*",
     "Judokrak":"*Localisation inconnue*",
     "Karaclée":"*Localisation inconnue*",
     "Larveyette":"\n - Bois Solidago",
     "Couverdure":"\n - Faire évoluer Larveyette",
     "Manternel":"\n - Faire évoluer Couverdure",
     "Venipatte":"\n - Bois Solidago",
     "Scobolide":"\n - Faire évoluer Venipatte",
     "Brutapode":"\n - Faire évoluer Scobolide",
     "Doudouvet":"*Localisation inconnue*",
     "Farfaduvet":"*Localisation inconnue*",
     "Chlorobule":"*Localisation inconnue*",
     "Fragilady":"*Localisation inconnue*",
     "Bargantua":"*Localisation inconnue*",
     "Mascaïman":"*Localisation inconnue*",
     "Escroco":"*Localisation inconnue*",
     "Crocorible":"*Localisation inconnue*",
     "Darumarond":"*Localisation inconnue*",
     "Darumacho":"*Localisation inconnue*",
     "Maracachi":"*Localisation inconnue*",
     "Crabicoque":"\n - Forêt Solidago",
     "Crabaraque":"\n - Faire évoluer Crabicoque",
     "Baggiguane":"*Localisation inconnue*",
     "Baggaïd":"*Localisation inconnue*",
     "Cryptéro":"*Localisation inconnue*",
     "Tutafeh":"*Localisation inconnue*",
     "Tutankafer":"*Localisation inconnue*",
     "Carapagos":"*Localisation inconnue*",
     "Mégapagos":"*Localisation inconnue*",
     "Arkéapti":"*Localisation inconnue*",
     "Aéroptéryx":"*Localisation inconnue*",
     "Miamiasme":"*Localisation inconnue*",
     "Miasmax":"*Localisation inconnue*",
     "Zorua":"*Localisation inconnue*",
     "Zoroark":"*Localisation inconnue*",
     "Chinchidou":"*Localisation inconnue*",
     "Pashmilla":"*Localisation inconnue*",
     "Scrutella":"*Localisation inconnue*",
     "Mesmérella":"*Localisation inconnue*",
     "Sidérella":"*Localisation inconnue*",
     "Nucléos":"*Localisation inconnue*",
     "Méios":"*Localisation inconnue*",
     "Symbios":"*Localisation inconnue*",
     "Couaneton":"*Localisation inconnue*",
     "Lakmécygne":"*Localisation inconnue*",
     "Sorbébé":"*Localisation inconnue*",
     "Sorboul":"*Localisation inconnue*",
     "Sorbouboul":"*Localisation inconnue*",
     "Vivaldaim":"*Localisation inconnue*",
     "Haydaim":"*Localisation inconnue*",
     "Emolga":"*Localisation inconnue*",
     "Carabing":"*Localisation inconnue*",
     "Lançargot":"*Localisation inconnue*",
     "Trompignon":"*Localisation inconnue*",
     "Gaulet":"*Localisation inconnue*",
     "Viskuse":"*Localisation inconnue*",
     "Moyade":"*Localisation inconnue*",
     "Mamanbo":"*Localisation inconnue*",
     "Statitik":"\n - Bois Solidago",
     "Mygavolt":"\n - Faire évoluer Statitik",
     "Grindur":"*Localisation inconnue*",
     "Noacier":"*Localisation inconnue*",
     "Tic":"*Localisation inconnue*",
     "Clic":"*Localisation inconnue*",
     "Cliticlic":"*Localisation inconnue*",
     "Anchwatt":"*Localisation inconnue*",
     "Lampéroie":"*Localisation inconnue*",
     "Ohmassacre":"*Localisation inconnue*",
     "Lewsor":"*Localisation inconnue*",
     "Neitram":"*Localisation inconnue*",
     "Funécire":"*Localisation inconnue*",
     "Mélancolux":"*Localisation inconnue*",
     "Lugulabre":"*Localisation inconnue*",
     "Coupenotte":"*Localisation inconnue*",
     "Incisache":"*Localisation inconnue*",
     "Tranchodon":"*Localisation inconnue*",
     "Polarhume":"*Localisation inconnue*",
     "Polagriffe":"*Localisation inconnue*",
     "Hexagel":"*Localisation inconnue*",
     "Escargaume":"*Localisation inconnue*",
     "Limaspeed":"*Localisation inconnue*",
     "Limonde":"*Localisation inconnue*",
     "Kungfouine":"*Localisation inconnue*",
     "Shaofouine":"*Localisation inconnue*",
     "Drakkarmin":"*Localisation inconnue*",
     "Gringolem":"*Localisation inconnue*",
     "Golemastoc":"*Localisation inconnue*",
     "Scalpion":"*Localisation inconnue*",
     "Scalproie":"*Localisation inconnue*",
     "Frison":"*Localisation inconnue*",
     "Furaiglon":"*Localisation inconnue*",
     "Gueriaigle":"*Localisation inconnue*",
     "Vostourno":"*Localisation inconnue*",
     "Vaututrice":"*Localisation inconnue*",
     "Aflamanoir":"*Localisation inconnue*",
     "Fermite":"*Localisation inconnue*",
     "Solochi":"*Localisation inconnue*",
     "Diamat":"*Localisation inconnue*",
     "Trioxhydre":"*Localisation inconnue*",
     "Pyronille":"- Bois Solidago (1%)",
     "Pyrax":"- Faire évoluer Pyronille",
     "Cobaltium":"*Localisation inconnue*",
     "Terrakium":"*Localisation inconnue*",
     "Viridium":"*Localisation inconnue*",
     "Boréas":"*Localisation inconnue*",
     "Fulguris":"*Localisation inconnue*",
     "Reshiram":"*Localisation inconnue*",
     "Zekrom":"*Localisation inconnue*",
     "Démétéros":"*Localisation inconnue*",
     "Kyurem":"*Localisation inconnue*",
     "Keldeo":"*Localisation inconnue*",
     "Meloetta":"*Localisation inconnue*",
     "Genesect":"*Localisation inconnue*",
     "Marisson":"\n - Centre de Recherches",
     "Boguérisse":"\n - Faire évoluer Marisson",
     "Blindépique":"\n - Faire évoluer Boguérisse",
     "Feunnec":"\n - Centre de Recherches",
     "Roussil":"\n - Faire évoluer Feunnec",
     "Goupelin":"\n - Faire évoluer Roussil",
     "Grenousse":"\n - Centre de Recherches",
     "Croâporal":"\n- Faire évoluer Grenousse",
     "Amphinobi":"\n - Faire évoluer Croâporal",
     "Sapereau":"*Localisation inconnue*",
     "Excavarenne":"*Localisation inconnue*",
     "Passerouge":"*Localisation inconnue*",
     "Braisillon":"*Localisation inconnue*",
     "Flambusard":"*Localisation inconnue*",
     "Lépidonille":"- Bois Solidago",
     "Pérégrain":"- Faire évoluer Lépidonille",
     "Prismillon":"- Faire évoluer Pérégrain",
     "Hélionceau":"*Localisation inconnue*",
     "Némélios":"*Localisation inconnue*",
     "Flabébé":"*Localisation inconnue*",
     "Floette":"*Localisation inconnue*",
     "Florges":"*Localisation inconnue*",
     "Cabriolaine":"*Localisation inconnue*",
     "Chevroum":"*Localisation inconnue*",
     "Pandespiègle":"*Localisation inconnue*",
     "Pandarbare":"*Localisation inconnue*",
     "Couafarel":"*Localisation inconnue*",
     "Psystigri":"*Localisation inconnue*",
     "Mistigrix":"*Localisation inconnue*",
     "Monorpale":"*Localisation inconnue*",
     "Dimoclès":"*Localisation inconnue*",
     "Exagide":"*Localisation inconnue*",
     "Fluvetin":"*Localisation inconnue*",
     "Cocotine":"*Localisation inconnue*",
     "Sucroquin":"*Localisation inconnue*",
     "Cupcanaille":"*Localisation inconnue*",
     "Sepiatop":"*Localisation inconnue*",
     "Sepiatroce":"*Localisation inconnue*",
     "Opermine":"*Localisation inconnue*",
     "Golgopathe":"*Localisation inconnue*",
     "Venalgue":"*Localisation inconnue*",
     "Kravarech":"*Localisation inconnue*",
     "Flingouste":"*Localisation inconnue*",
     "Gamblast":"*Localisation inconnue*",
     "Galvaran":"*Localisation inconnue*",
     "Iguolta":"*Localisation inconnue*",
     "Ptyranidur":"*Localisation inconnue*",
     "Rexillius":"*Localisation inconnue*",
     "Amagara":"*Localisation inconnue*",
     "Dragmara":"*Localisation inconnue*",
     "Nymphali":"*Localisation inconnue*",
     "Brutalibré":"*Localisation inconnue*",
     "Dedenne":"*Localisation inconnue*",
     "Strassie":"*Localisation inconnue*",
     "Mucuscule":"*Localisation inconnue*",
     "Colimucus":"*Localisation inconnue*",
     "Muplodocus":"*Localisation inconnue*",
     "Trousselin":"*Localisation inconnue*",
     "Brocélôme":"*Localisation inconnue*",
     "Desséliande":"*Localisation inconnue*",
     "Pitrouille":"*Localisation inconnue*",
     "Banshitrouye":"*Localisation inconnue*",
     "Grelaçon":"*Localisation inconnue*",
     "Séracrawl":"*Localisation inconnue*",
     "Sonistrelle":"*Localisation inconnue*",
     "Bruyverne":"*Localisation inconnue*",
     "Xerneas":"*Localisation inconnue*",
     "Yveltal":"*Localisation inconnue*",
     "Zygarde":"*Localisation inconnue*",
     "Diancie":"*Localisation inconnue*",
     "Hoopa":"*Localisation inconnue*",
     "Volcanion":"*Localisation inconnue*",
     "Brindibou":"\n - Centre de Recherches",
     "Efflèche":"\n - Faire évoluer Brindibou",
     "Archéduc":"\n - Faire évoluer Efflèche",
     "Flamiaou":"\n - Centre de Recherches",
     "Matoufeu":"\n - Faire évoluer Flamiaou",
     "Félinferno":"\n - Faire évoluer Matoufeu",
     "Otaquin":"\n - Centre de Recherches",
     "Otarlette":"\n - Faire évoluer Otaquin",
     "Oratoria":"\n - Faire évoluer Otarlette",
     "Picassaut":"*Localisation inconnue*",
     "Piclairon":"*Localisation inconnue*",
     "Bazoucan":"*Localisation inconnue*",
     "Manglouton":"*Localisation inconnue*",
     "Argouste":"*Localisation inconnue*",
     "Larvibule":"\n - Bois Solidago",
     "Chrysapile":"\n - Faire évoluer Larvibule",
     "Lucanon":"\n - Faire évoluer Chrysapile",
     "Crabagarre":"*Localisation inconnue*",
     "Crabominable":"*Localisation inconnue*",
     "Plumeline":"*Localisation inconnue*",
     "Bombydou":"\n - Bois Solidago",
     "Rubombelle":"\n - Faire évoluer Bombydou",
     "Rocabot":"*Localisation inconnue*",
     "Lougaroc":"*Localisation inconnue*",
     "Froussardine":"*Localisation inconnue*",
     "Vorastérie":"*Localisation inconnue*",
     "Prédastérie":"*Localisation inconnue*",
     "Tiboudet":"*Localisation inconnue*",
     "Bourrinos":"*Localisation inconnue*",
     "Araqua":"\n- Bois Solidago",
     "Tarenbulle":"\n- Faire évoluer Araqua",
     "Mimantis":"*Localisation inconnue*",
     "Floramantis":"*Localisation inconnue*",
     "Spododo":"*Localisation inconnue*",
     "Lampignon":"*Localisation inconnue*",
     "Tritox":"*Localisation inconnue*",
     "Malamandre":"*Localisation inconnue*",
     "Nounourson":"*Localisation inconnue*",
     "Chelours":"*Localisation inconnue*",
     "Croquine":"*Localisation inconnue*",
     "Candine":"*Localisation inconnue*",
     "Sucreine":"*Localisation inconnue*",
     "Guérilande":"*Localisation inconnue*",
     "Gouroutan":"*Localisation inconnue*",
     "Quartermac":"*Localisation inconnue*",
     "Sovkipou":"*Localisation inconnue*",
     "Sarmuraï":"*Localisation inconnue*",
     "Bacabouh":"*Localisation inconnue*",
     "Trépassable":"*Localisation inconnue*",
     "Concombaffe":"*Localisation inconnue*",
     "Type:0":"*Localisation inconnue*",
     "Silvallié":"*Localisation inconnue*",
     "Météno":"*Localisation inconnue*",
     "Dodoala":"*Localisation inconnue*",
     "Boumata":"*Localisation inconnue*",
     "Togedemaru":"*Localisation inconnue*",
     "Mimiqui":"*Localisation inconnue*",
     "Denticrisse":"*Localisation inconnue*",
     "Draïeul":"*Localisation inconnue*",
     "Sinistrail":"*Localisation inconnue*",
     "Bébécaille":"*Localisation inconnue*",
     "Écaïd":"*Localisation inconnue*",
     "Ékaïser":"*Localisation inconnue*",
     "Tokorico":"*Localisation inconnue*",
     "Tokopiyon":"*Localisation inconnue*",
     "Tokotoro":"*Localisation inconnue*",
     "Tokopisco":"*Localisation inconnue*",
     "Cosmog":"*Localisation inconnue*",
     "Cosmovum":"*Localisation inconnue*",
     "Solgaleo":"*Localisation inconnue*",
     "Lunala":"*Localisation inconnue*",
     "Zéroïd":"*Localisation inconnue*",
     "Mouscoto":"*Localisation inconnue*",
     "Cancrelove":"*Localisation inconnue*",
     "Câblifère":"*Localisation inconnue*",
     "Bamboiselle":"*Localisation inconnue*",
     "Katagami":"*Localisation inconnue*",
     "Engloutyran":"*Localisation inconnue*",
     "Necrozma":"*Localisation inconnue*",
     "Magearna":"*Localisation inconnue*",
     "Marshadow":"*Localisation inconnue*",
     "Vémini":"*Localisation inconnue*",
     "Mandrillon":"*Localisation inconnue*",
     "Ama-Ama":"*Localisation inconnue*",
     "Pierroteknik":"*Localisation inconnue*",
     "Zeraora":"*Localisation inconnue*",
     "Meltan":"*Localisation inconnue*",
     "Melmetal":"*Localisation inconnue*",
     "Ouistempo":"\n - Centre de Recherches",
     "Badabouin":"\n - Faire évoluer Ouistempo",
     "Gorythmic":"\n - Faire évoluer Badabouin",
     "Flambino":"*\n - Centre de Recherches",
     "Lapyro":"\n - Faire évoluer Flambino",
     "Pyrobut":"\n - Faire évoluer Lapyro",
     "Larméléon":"\n - Centre de Recherches",
     "Arrozard":"\n - Faire évoluer Larméléon",
     "Lézargus":"\n - Faire évoluer Arrozard",
     "Rongourmand":"*Localisation inconnue*",
     "Rongrigou":"*Localisation inconnue*",
     "Minisange":"*Localisation inconnue*",
     "Bleuseille":"*Localisation inconnue*",
     "Corvaillus":"*Localisation inconnue*",
     "Larvadar":"\n- Bois Solidago",
     "Coléodôme":"\n- Faire évoluer Larvadar",
     "Astronelle":"\n- Faire évoluer Coléodôme",
     "Goupilou":"*Localisation inconnue*",
     "Roublenard":"*Localisation inconnue*",
     "Tournicoton":"*Localisation inconnue*",
     "Blancoton":"*Localisation inconnue*",
     "Moumouton":"*Localisation inconnue*",
     "Moumouflon":"*Localisation inconnue*",
     "Khélocrok":"*Localisation inconnue*",
     "Torgamord":"*Localisation inconnue*",
     "Voltoutou":"*Localisation inconnue*",
     "Fulgudog":"*Localisation inconnue*",
     "Charbi":"*Localisation inconnue*",
     "Wagomine":"*Localisation inconnue*",
     "Monthracite":"*Localisation inconnue*",
     "Verpom":"*Localisation inconnue*",
     "Pomdrapi":"*Localisation inconnue*",
     "Dratatin":"*Localisation inconnue*",
     "Dunaja":"*Localisation inconnue*",
     "Dunaconda":"*Localisation inconnue*",
     "Nigosier":"*Localisation inconnue*",
     "Embrochet":"*Localisation inconnue*",
     "Hastacuda":"*Localisation inconnue*",
     "Toxizap":"*Localisation inconnue*",
     "Salarsen":"*Localisation inconnue*",
     "Grillepattes":"*Localisation inconnue*",
     "Scolocendre":"*Localisation inconnue*",
     "Poulpaf":"*Localisation inconnue*",
     "Krakos":"*Localisation inconnue*",
     "Théffroi":"*Localisation inconnue*",
     "Polthégeist":"*Localisation inconnue*",
     "Bibichut":"*Localisation inconnue*",
     "Chapotus":"*Localisation inconnue*",
     "Sorcilence":"*Localisation inconnue*",
     "Grimalin":"*Localisation inconnue*",
     "Fourbelin":"*Localisation inconnue*",
     "Angoliath":"*Localisation inconnue*",
     "Ixon":"*Localisation inconnue*",
     "Berserkatt":"*Localisation inconnue*",
     "Corayôme":"*Localisation inconnue*",
     "Palarticho":"*Localisation inconnue*",
     "M. Glaquette":"*Localisation inconnue*",
     "Tutétékri":"*Localisation inconnue*",
     "Crèmy":"*Localisation inconnue*",
     "Charmilly":"*Localisation inconnue*",
     "Hexadron":"*Localisation inconnue*",
     "Wattapik":"*Localisation inconnue*",
     "Frissonille":"\n - Bois Solidago",
     "Beldeneige":"\n - Faire évoluer Frissonille",
     "Dolman":"*Localisation inconnue*",
     "Bekaglaçon":"*Localisation inconnue*",
     "Wimessir":"*Localisation inconnue*",
     "Morpeko":"*Localisation inconnue*",
     "Charibari":"*Localisation inconnue*",
     "Pachyradjah":"*Localisation inconnue*",
     "Galvagon":"*Localisation inconnue*",
     "Galvagla":"*Localisation inconnue*",
     "Hydragon":"*Localisation inconnue*",
     "Hydragla":"*Localisation inconnue*",
     "Duralugon":"*Localisation inconnue*",
     "Fantyrm":"*Localisation inconnue*",
     "Dispareptil":"*Localisation inconnue*",
     "Lanssorien":"*Localisation inconnue*",
     "Zacian":"*Localisation inconnue*",
     "Zamazenta":"*Localisation inconnue*",
     "Éthernatos":"*Localisation inconnue*",
     "Wushours":"*Localisation inconnue*",
     "Shifours":"*Localisation inconnue*",
     "Zarude":"*Localisation inconnue*",
     "Regieleki":"*Localisation inconnue*",
     "Regidrago":"*Localisation inconnue*",
     "Blizzeval":"*Localisation inconnue*",
     "Spectreval":"*Localisation inconnue*",
     "Sylveroy":"*Localisation inconnue*",
}
data_fr={"Bulbizarre":"Bulbasaur","Herbizarre":"Ivysaur","Florizarre":"Venusaur","Salamèche":"Charmander","Reptincel":"Charmeleon","Dracaufeu":"Charizard","Carapuce":"Squirtle","Carabaffe":"Wartortle","Tortank":"Blastoise","Chenipan":"Caterpie","Chrysacier":"Metapod","Papilusion":"Butterfree","Aspicot":"Weedle","Coconfort":"Kakuna","Dardargnan":"Beedrill","Roucool":"Pidgey","Roucoups":"Pidgeotto","Roucarnage":"Pidgeot","Rattata":"Rattata","Rattatac":"Raticate","Piafabec":"Spearow","Rapasdepic":"Fearow","Abo":"Ekans","Arbok":"Arbok","Pikachu":"Pikachu","Raichu":"Raichu","Sabelette":"Sandshrew","Sablaireau":"Sandslash","Nidoran♀":"Nidoran♀","Nidorina":"Nidorina","Nidoqueen":"Nidoqueen","Nidoran♂":"Nidoran♂","Nidorino":"Nidorino","Nidoking":"Nidoking","Mélofée":"Clefairy","Mélodelfe":"Clefable","Goupix":"Vulpix","Feunard":"Ninetales","Rondoudou":"Jigglypuff","Grodoudou":"Wigglytuff","Nosferapti":"Zubat","Nosferalto":"Golbat","Mystherbe":"Oddish","Ortide":"Gloom","Rafflesia":"Vileplume","Paras":"Paras","Parasect":"Parasect","Mimitoss":"Venonat","Aéromite":"Venomoth","Taupiqueur":"Diglett","Triopikeur":"Dugtrio","Miaouss":"Meowth","Persian":"Persian","Psykokwak":"Psyduck","Akwakwak":"Golduck","Férosinge":"Mankey","Colossinge":"Primeape","Caninos":"Growlithe","Arcanin":"Arcanine","Ptitard":"Poliwag","Têtarte":"Poliwhirl","Tartard":"Poliwrath","Abra":"Abra","Kadabra":"Kadabra","Alakazam":"Alakazam","Machoc":"Machop","Machopeur":"Machoke","Mackogneur":"Machamp","Chétiflor":"Bellsprout","Boustiflor":"Weepinbell","Empiflor":"Victreebel","Tentacool":"Tentacool","Tentacruel":"Tentacruel","Racaillou":"Geodude","Gravalanch":"Graveler","Grolem":"Golem","Ponyta":"Ponyta","Galopa":"Rapidash","Ramoloss":"Slowpoke","Flagadoss":"Slowbro","Magnéti":"Magnemite","Magnéton":"Magneton","Canarticho":"Farfetch’d","Doduo":"Doduo","Dodrio":"Dodrio","Otaria":"Seel","Lamantine":"Dewgong","Tadmorv":"Grimer","Grotadmorv":"Muk","Kokiyas":"Shellder","Crustabri":"Cloyster","Fantominus":"Gastly","Spectrum":"Haunter","Ectoplasma":"Gengar","Onix":"Onix","Soporifik":"Drowzee","Hypnomade":"Hypno","Krabby":"Krabby","Krabboss":"Kingler","Voltorbe":"Voltorb","Électrode":"Electrode","Noeunoeuf":"Exeggcute","Noadkoko":"Exeggutor","Osselait":"Cubone","Ossatueur":"Marowak","Kicklee":"Hitmonlee","Tygnon":"Hitmonchan","Excelangue":"Lickitung","Smogo":"Koffing","Smogogo":"Weezing","Rhinocorne":"Rhyhorn","Rhinoféros":"Rhydon","Leveinard":"Chansey","Saquedeneu":"Tangela","Kangourex":"Kangaskhan","Hypotrempe":"Horsea","Hypocéan":"Seadra","Poissirène":"Goldeen","Poissoroy":"Seaking","Stari":"Staryu","Staross":"Starmie","M. Mime":"Mr. Mime","Insécateur":"Scyther","Lippoutou":"Jynx","Élektek":"Electabuzz","Magmar":"Magmar","Scarabrute":"Pinsir","Tauros":"Tauros","Magicarpe":"Magikarp","Léviator":"Gyarados","Lokhlass":"Lapras","Métamorph":"Ditto","Évoli":"Eevee","Aquali":"Vaporeon","Voltali":"Jolteon","Pyroli":"Flareon","Porygon":"Porygon","Amonita":"Omanyte","Amonistar":"Omastar","Kabuto":"Kabuto","Kabutops":"Kabutops","Ptéra":"Aerodactyl","Ronflex":"Snorlax","Artikodin":"Articuno","Électhor":"Zapdos","Sulfura":"Moltres","Minidraco":"Dratini","Draco":"Dragonair","Dracolosse":"Dragonite","Mewtwo":"Mewtwo","Mew":"Mew","Germignon":"Chikorita","Macronium":"Bayleef","Méganium":"Meganium","Héricendre":"Cyndaquil","Feurisson":"Quilava","Typhlosion":"Typhlosion","Kaiminus":"Totodile","Crocrodil":"Croconaw","Aligatueur":"Feraligatr","Fouinette":"Sentret","Fouinar":"Furret","Hoothoot":"Hoothoot","Noarfang":"Noctowl","Coxy":"Ledyba","Coxyclaque":"Ledian","Mimigal":"Spinarak","Migalos":"Ariados","Nostenfer":"Crobat","Loupio":"Chinchou","Lanturn":"Lanturn","Pichu":"Pichu","Mélo":"Cleffa","Toudoudou":"Igglybuff","Togepi":"Togepi","Togetic":"Togetic","Natu":"Natu","Xatu":"Xatu","Wattouat":"Mareep","Lainergie":"Flaaffy","Pharamp":"Ampharos","Joliflor":"Bellossom","Marill":"Marill","Azumarill":"Azumarill","Simularbre":"Sudowoodo","Tarpaud":"Politoed","Granivol":"Hoppip","Floravol":"Skiploom","Cotovol":"Jumpluff","Capumain":"Aipom","Tournegrin":"Sunkern","Héliatronc":"Sunflora","Yanma":"Yanma","Axoloto":"Wooper","Maraiste":"Quagsire","Mentali":"Espeon","Noctali":"Umbreon","Cornèbre":"Murkrow","Roigada":"Slowking","Feuforêve":"Misdreavus","Zarbi":"Unown","Qulbutoké":"Wobbuffet","Girafarig":"Girafarig","Pomdepik":"Pineco","Foretress":"Forretress","Insolourdo":"Dunsparce","Scorplane":"Gligar","Steelix":"Steelix","Snubbull":"Snubbull","Granbull":"Granbull","Qwilfish":"Qwilfish","Cizayox":"Scizor","Caratroc":"Shuckle","Scarhino":"Heracross","Farfuret":"Sneasel","Teddiursa":"Teddiursa","Ursaring":"Ursaring","Limagma":"Slugma","Volcaropod":"Magcargo","Marcacrin":"Swinub","Cochignon":"Piloswine","Corayon":"Corsola","Rémoraid":"Remoraid","Octillery":"Octillery","Cadoizo":"Delibird","Démanta":"Mantine","Airmure":"Skarmory","Malosse":"Houndour","Démolosse":"Houndoom","Hyporoi":"Kingdra","Phanpy":"Phanpy","Donphan":"Donphan","Porygon2":"Porygon2","Cerfrousse":"Stantler","Queulorior":"Smeargle","Debugant":"Tyrogue","Kapoera":"Hitmontop","Lippouti":"Smoochum","Élekid":"Elekid","Magby":"Magby","Écrémeuh":"Miltank","Leuphorie":"Blissey","Raikou":"Raikou","Entei":"Entei","Suicune":"Suicune","Embrylex":"Larvitar","Ymphect":"Pupitar","Tyranocif":"Tyranitar","Lugia":"Lugia","Ho-Oh":"Ho-Oh","Celebi":"Celebi","Arcko":"Treecko","Massko":"Grovyle","Jungko":"Sceptile","Poussifeu":"Torchic","Galifeu":"Combusken","Braségali":"Blaziken","Gobou":"Mudkip","Flobio":"Marshtomp","Laggron":"Swampert","Medhyèna":"Poochyena","Grahyèna":"Mightyena","Zigzaton":"Zigzagoon","Linéon":"Linoone","Chenipotte":"Wurmple","Armulys":"Silcoon","Charmillon":"Beautifly","Blindalys":"Cascoon","Papinox":"Dustox","Nénupiot":"Lotad","Lombre":"Lombre","Ludicolo":"Ludicolo","Grainipiot":"Seedot","Pifeuil":"Nuzleaf","Tengalice":"Shiftry","Nirondelle":"Taillow","Hélédelle":"Swellow","Goélise":"Wingull","Bekipan":"Pelipper","Tarsal":"Ralts","Kirlia":"Kirlia","Gardevoir":"Gardevoir","Arakdo":"Surskit","Maskadra":"Masquerain","Balignon":"Shroomish","Chapignon":"Breloom","Parecool":"Slakoth","Vigoroth":"Vigoroth","Monaflèmit":"Slaking","Ningale":"Nincada","Ninjask":"Ninjask","Munja":"Shedinja","Chuchmur":"Whismur","Ramboum":"Loudred","Brouhabam":"Exploud","Makuhita":"Makuhita","Hariyama":"Hariyama","Azurill":"Azurill","Tarinor":"Nosepass","Skitty":"Skitty","Delcatty":"Delcatty","Ténéfix":"Sableye","Mysdibule":"Mawile","Galekid":"Aron","Galegon":"Lairon","Galeking":"Aggron","Méditikka":"Meditite","Charmina":"Medicham","Dynavolt":"Electrike","Élecsprint":"Manectric","Posipi":"Plusle","Négapi":"Minun","Muciole":"Volbeat","Lumivole":"Illumise","Rosélia":"Roselia","Gloupti":"Gulpin","Avaltout":"Swalot","Carvanha":"Carvanha","Sharpedo":"Sharpedo","Wailmer":"Wailmer","Wailord":"Wailord","Chamallot":"Numel","Camérupt":"Camerupt","Chartor":"Torkoal","Spoink":"Spoink","Groret":"Grumpig","Spinda":"Spinda","Kraknoix":"Trapinch","Vibraninf":"Vibrava","Libégon":"Flygon","Cacnea":"Cacnea","Cacturne":"Cacturne","Tylton":"Swablu","Altaria":"Altaria","Mangriff":"Zangoose","Séviper":"Seviper","Séléroc":"Lunatone","Solaroc":"Solrock","Barloche":"Barboach","Barbicha":"Whiscash","Écrapince":"Corphish","Colhomard":"Crawdaunt","Balbuto":"Baltoy","Kaorine":"Claydol","Lilia":"Lileep","Vacilys":"Cradily","Anorith":"Anorith","Armaldo":"Armaldo","Barpau":"Feebas","Milobellus":"Milotic","Morphéo":"Castform","Kecleon":"Kecleon","Polichombr":"Shuppet","Branette":"Banette","Skelénox":"Duskull","Téraclope":"Dusclops","Tropius":"Tropius","Éoko":"Chimecho","Absol":"Absol","Okéoké":"Wynaut","Stalgamin":"Snorunt","Oniglali":"Glalie","Obalie":"Spheal","Phogleur":"Sealeo","Kaimorse":"Walrein","Coquiperl":"Clamperl","Serpang":"Huntail","Rosabyss":"Gorebyss","Relicanth":"Relicanth","Lovdisc":"Luvdisc","Draby":"Bagon","Drackhaus":"Shelgon","Drattak":"Salamence","Terhal":"Beldum","Métang":"Metang","Métalosse":"Metagross","Regirock":"Regirock","Regice":"Regice","Registeel":"Registeel","Latias":"Latias","Latios":"Latios","Kyogre":"Kyogre","Groudon":"Groudon","Rayquaza":"Rayquaza","Jirachi":"Jirachi","Deoxys":"Deoxys","Tortipouss":"Turtwig","Boskara":"Grotle","Torterra":"Torterra","Ouisticram":"Chimchar","Chimpenfeu":"Monferno","Simiabraz":"Infernape","Tiplouf":"Piplup","Prinplouf":"Prinplup","Pingoléon":"Empoleon","Étourmi":"Starly","Étourvol":"Staravia","Étouraptor":"Staraptor","Keunotor":"Bidoof","Castorno":"Bibarel","Crikzik":"Kricketot","Mélokrik":"Kricketune","Lixy":"Shinx","Luxio":"Luxio","Luxray":"Luxray","Rozbouton":"Budew","Roserade":"Roserade","Kranidos":"Cranidos","Charkos":"Rampardos","Dinoclier":"Shieldon","Bastiodon":"Bastiodon","Cheniti":"Burmy","Cheniselle":"Wormadam","Papilord":"Mothim","Apitrini":"Combee","Apireine":"Vespiquen","Pachirisu":"Pachirisu","Mustébouée":"Buizel","Mustéflott":"Floatzel","Ceribou":"Cherubi","Ceriflor":"Cherrim","Sancoki":"Shellos","Tritosor":"Gastrodon","Capidextre":"Ambipom","Baudrive":"Drifloon","Grodrive":"Drifblim","Laporeille":"Buneary","Lockpin":"Lopunny","Magirêve":"Mismagius","Corboss":"Honchkrow","Chaglam":"Glameow","Chaffreux":"Purugly","Korillon":"Chingling","Moufouette":"Stunky","Moufflair":"Skuntank","Archéomire":"Bronzor","Archéodong":"Bronzong","Manzaï":"Bonsly","Mime Jr.":"Mime Jr.","Ptiravi":"Happiny","Pijako":"Chatot","Spiritomb":"Spiritomb","Griknot":"Gible","Carmache":"Gabite","Carchacrok":"Garchomp","Goinfrex":"Munchlax","Riolu":"Riolu","Lucario":"Lucario","Hippopotas":"Hippopotas","Hippodocus":"Hippowdon","Rapion":"Skorupi","Drascore":"Drapion","Cradopaud":"Croagunk","Coatox":"Toxicroak","Vortente":"Carnivine","Écayon":"Finneon","Luminéon":"Lumineon","Babimanta":"Mantyke","Blizzi":"Snover","Blizzaroi":"Abomasnow","Dimoret":"Weavile","Magnézone":"Magnezone","Coudlangue":"Lickilicky","Rhinastoc":"Rhyperior","Bouldeneu":"Tangrowth","Élekable":"Electivire","Maganon":"Magmortar","Togekiss":"Togekiss","Yanmega":"Yanmega","Phyllali":"Leafeon","Givrali":"Glaceon","Scorvol":"Gliscor","Mammochon":"Mamoswine","Porygon-Z":"Porygon-Z","Gallame":"Gallade","Tarinorme":"Probopass","Noctunoir":"Dusknoir","Momartik":"Froslass","Motisma":"Rotom","Créhelf":"Uxie","Créfollet":"Mesprit","Créfadet":"Azelf","Dialga":"Dialga","Palkia":"Palkia","Heatran":"Heatran","Regigigas":"Regigigas","Giratina":"Giratina","Cresselia":"Cresselia","Phione":"Phione","Manaphy":"Manaphy","Darkrai":"Darkrai","Shaymin":"Shaymin","Arceus":"Arceus","Victini":"Victini","Vipélierre":"Snivy","Lianaja":"Servine","Majaspic":"Serperior","Gruikui":"Tepig","Grotichon":"Pignite","Roitiflam":"Emboar","Moustillon":"Oshawott","Mateloutre":"Dewott","Clamiral":"Samurott","Ratentif":"Patrat","Miradar":"Watchog","Ponchiot":"Lillipup","Ponchien":"Herdier","Mastouffe":"Stoutland","Chacripan":"Purrloin","Léopardus":"Liepard","Feuillajou":"Pansage","Feuiloutan":"Simisage","Flamajou":"Pansear","Flamoutan":"Simisear","Flotajou":"Panpour","Flotoutan":"Simipour","Munna":"Munna","Mushana":"Musharna","Poichigeon":"Pidove","Colombeau":"Tranquill","Déflaisan":"Unfezant","Zébibron":"Blitzle","Zéblitz":"Zebstrika","Nodulithe":"Roggenrola","Géolithe":"Boldore","Gigalithe":"Gigalith","Chovsourir":"Woobat","Rhinolove":"Swoobat","Rototaupe":"Drilbur","Minotaupe":"Excadrill","Nanméouïe":"Audino","Charpenti":"Timburr","Ouvrifier":"Gurdurr","Bétochef":"Conkeldurr","Tritonde":"Tympole","Batracné":"Palpitoad","Crapustule":"Seismitoad","Judokrak":"Throh","Karaclée":"Sawk","Larveyette":"Sewaddle","Couverdure":"Swadloon","Manternel":"Leavanny","Venipatte":"Venipede","Scobolide":"Whirlipede","Brutapode":"Scolipede","Doudouvet":"Cottonee","Farfaduvet":"Whimsicott","Chlorobule":"Petilil","Fragilady":"Lilligant","Bargantua":"Basculin","Mascaïman":"Sandile","Escroco":"Krokorok","Crocorible":"Krookodile","Darumarond":"Darumaka","Darumacho":"Darmanitan","Maracachi":"Maractus","Crabicoque":"Dwebble","Crabaraque":"Crustle","Baggiguane":"Scraggy","Baggaïd":"Scrafty","Cryptéro":"Sigilyph","Tutafeh":"Yamask","Tutankafer":"Cofagrigus","Carapagos":"Tirtouga","Mégapagos":"Carracosta","Arkéapti":"Archen","Aéroptéryx":"Archeops","Miamiasme":"Trubbish","Miasmax":"Garbodor","Zorua":"Zorua","Zoroark":"Zoroark","Chinchidou":"Minccino","Pashmilla":"Cinccino","Scrutella":"Gothita","Mesmérella":"Gothorita","Sidérella":"Gothitelle","Nucléos":"Solosis","Méios":"Duosion","Symbios":"Reuniclus","Couaneton":"Ducklett","Lakmécygne":"Swanna","Sorbébé":"Vanillite","Sorboul":"Vanillish","Sorbouboul":"Vanilluxe","Vivaldaim":"Deerling","Haydaim":"Sawsbuck","Emolga":"Emolga","Carabing":"Karrablast","Lançargot":"Escavalier","Trompignon":"Foongus","Gaulet":"Amoonguss","Viskuse":"Frillish","Moyade":"Jellicent","Mamanbo":"Alomomola","Statitik":"Joltik","Mygavolt":"Galvantula","Grindur":"Ferroseed","Noacier":"Ferrothorn","Tic":"Klink","Clic":"Klang","Cliticlic":"Klinklang","Anchwatt":"Tynamo","Lampéroie":"Eelektrik","Ohmassacre":"Eelektross","Lewsor":"Elgyem","Neitram":"Beheeyem","Funécire":"Litwick","Mélancolux":"Lampent","Lugulabre":"Chandelure","Coupenotte":"Axew","Incisache":"Fraxure","Tranchodon":"Haxorus","Polarhume":"Cubchoo","Polagriffe":"Beartic","Hexagel":"Cryogonal","Escargaume":"Shelmet","Limaspeed":"Accelgor","Limonde":"Stunfisk","Kungfouine":"Mienfoo","Shaofouine":"Mienshao","Drakkarmin":"Druddigon","Gringolem":"Golett","Golemastoc":"Golurk","Scalpion":"Pawniard","Scalproie":"Bisharp","Frison":"Bouffalant","Furaiglon":"Rufflet","Gueriaigle":"Braviary","Vostourno":"Vullaby","Vaututrice":"Mandibuzz","Aflamanoir":"Heatmor","Fermite":"Durant","Solochi":"Deino","Diamat":"Zweilous","Trioxhydre":"Hydreigon","Pyronille":"Larvesta","Pyrax":"Volcarona","Cobaltium":"Cobalion","Terrakium":"Terrakion","Viridium":"Virizion","Boréas":"Tornadus","Fulguris":"Thundurus","Reshiram":"Reshiram","Zekrom":"Zekrom","Démétéros":"Landorus","Kyurem":"Kyurem","Keldeo":"Keldeo","Meloetta":"Meloetta","Genesect":"Genesect","Marisson":"Chespin","Boguérisse":"Quilladin","Blindépique":"Chesnaught","Feunnec":"Fennekin","Roussil":"Braixen","Goupelin":"Delphox","Grenousse":"Froakie","Croâporal":"Frogadier","Amphinobi":"Greninja","Sapereau":"Bunnelby","Excavarenne":"Diggersby","Passerouge":"Fletchling","Braisillon":"Fletchinder","Flambusard":"Talonflame","Lépidonille":"Scatterbug","Pérégrain":"Spewpa","Prismillon":"Vivillon","Hélionceau":"Litleo","Némélios":"Pyroar","Flabébé":"Flabébé","Floette":"Floette","Florges":"Florges","Cabriolaine":"Skiddo","Chevroum":"Gogoat","Pandespiègle":"Pancham","Pandarbare":"Pangoro","Couafarel":"Furfrou","Psystigri":"Espurr","Mistigrix":"Meowstic","Monorpale":"Honedge","Dimoclès":"Doublade","Exagide":"Aegislash","Fluvetin":"Spritzee","Cocotine":"Aromatisse","Sucroquin":"Swirlix","Cupcanaille":"Slurpuff","Sepiatop":"Inkay","Sepiatroce":"Malamar","Opermine":"Binacle","Golgopathe":"Barbaracle","Venalgue":"Skrelp","Kravarech":"Dragalge","Flingouste":"Clauncher","Gamblast":"Clawitzer","Galvaran":"Helioptile","Iguolta":"Heliolisk","Ptyranidur":"Tyrunt","Rexillius":"Tyrantrum","Amagara":"Amaura","Dragmara":"Aurorus","Nymphali":"Sylveon","Brutalibré":"Hawlucha","Dedenne":"Dedenne","Strassie":"Carbink","Mucuscule":"Goomy","Colimucus":"Sliggoo","Muplodocus":"Goodra","Trousselin":"Klefki","Brocélôme":"Phantump","Desséliande":"Trevenant","Pitrouille":"Pumpkaboo","Banshitrouye":"Gourgeist","Grelaçon":"Bergmite","Séracrawl":"Avalugg","Sonistrelle":"Noibat","Bruyverne":"Noivern","Xerneas":"Xerneas","Yveltal":"Yveltal","Zygarde":"Zygarde","Diancie":"Diancie","Hoopa":"Hoopa","Volcanion":"Volcanion","Brindibou":"Rowlet","Efflèche":"Dartrix","Archéduc":"Decidueye","Flamiaou":"Litten","Matoufeu":"Torracat","Félinferno":"Incineroar","Otaquin":"Popplio","Otarlette":"Brionne","Oratoria":"Primarina","Picassaut":"Pikipek","Piclairon":"Trumbeak","Bazoucan":"Toucannon","Manglouton":"Yungoos","Argouste":"Gumshoos","Larvibule":"Grubbin","Chrysapile":"Charjabug","Lucanon":"Vikavolt","Crabagarre":"Crabrawler","Crabominable":"Crabominable","Plumeline":"Oricorio","Bombydou":"Cutiefly","Rubombelle":"Ribombee","Rocabot":"Rockruff","Lougaroc":"Lycanroc","Froussardine":"Wishiwashi","Vorastérie":"Mareanie","Prédastérie":"Toxapex","Tiboudet":"Mudbray","Bourrinos":"Mudsdale","Araqua":"Dewpider","Tarenbulle":"Araquanid","Mimantis":"Fomantis","Floramantis":"Lurantis","Spododo":"Morelull","Lampignon":"Shiinotic","Tritox":"Salandit","Malamandre":"Salazzle","Nounourson":"Stufful","Chelours":"Bewear","Croquine":"Bounsweet","Candine":"Steenee","Sucreine":"Tsareena","Guérilande":"Comfey","Gouroutan":"Oranguru","Quartermac":"Passimian","Sovkipou":"Wimpod","Sarmuraï":"Golisopod","Bacabouh":"Sandygast","Trépassable":"Palossand","Concombaffe":"Pyukumuku","Type:0":"Type: Null","Silvallié":"Silvally","Météno":"Minior","Dodoala":"Komala","Boumata":"Turtonator","Togedemaru":"Togedemaru","Mimiqui":"Mimikyu","Denticrisse":"Bruxish","Draïeul":"Drampa","Sinistrail":"Dhelmise","Bébécaille":"Jangmo-o","Écaïd":"Hakamo-o","Ékaïser":"Kommo-o","Tokorico":"Tapu Koko","Tokopiyon":"Tapu Lele","Tokotoro":"Tapu Bulu","Tokopisco":"Tapu Fini","Cosmog":"Cosmog","Cosmovum":"Cosmoem","Solgaleo":"Solgaleo","Lunala":"Lunala","Zéroïd":"Nihilego","Mouscoto":"Buzzwole","Cancrelove":"Pheromosa","Câblifère":"Xurkitree","Bamboiselle":"Celesteela","Katagami":"Kartana","Engloutyran":"Guzzlord","Necrozma":"Necrozma","Magearna":"Magearna","Marshadow":"Marshadow","Vémini":"Poipole","Mandrillon":"Naganadel","Ama-Ama":"Stakataka","Pierroteknik":"Blacephalon","Zeraora":"Zeraora","Meltan":"Meltan","Melmetal":"Melmetal","Ouistempo":"Grookey","Badabouin":"Thwackey","Gorythmic":"Rillaboom","Flambino":"Scorbunny","Lapyro":"Raboot","Pyrobut":"Cinderace","Larméléon":"Sobble","Arrozard":"Drizzile","Lézargus":"Inteleon","Rongourmand":"Skwovet","Rongrigou":"Greedent","Minisange":"Rookidee","Bleuseille":"Corvisquire","Corvaillus":"Corviknight","Larvadar":"Blipbug","Coléodôme":"Dottler","Astronelle":"Orbeetle","Goupilou":"Nickit","Roublenard":"Thievul","Tournicoton":"Gossifleur","Blancoton":"Eldegoss","Moumouton":"Wooloo","Moumouflon":"Dubwool","Khélocrok":"Chewtle","Torgamord":"Drednaw","Voltoutou":"Yamper","Fulgudog":"Boltund","Charbi":"Rolycoly","Wagomine":"Carkol","Monthracite":"Coalossal","Verpom":"Applin","Pomdrapi":"Flapple","Dratatin":"Appletun","Dunaja":"Silicobra","Dunaconda":"Sandaconda","Nigosier":"Cramorant","Embrochet":"Arrokuda","Hastacuda":"Barraskewda","Toxizap":"Toxel","Salarsen":"Toxtricity","Grillepattes":"Sizzlipede","Scolocendre":"Centiskorch","Poulpaf":"Clobbopus","Krakos":"Grapploct","Théffroi":"Sinistea","Polthégeist":"Polteageist","Bibichut":"Hatenna","Chapotus":"Hattrem","Sorcilence":"Hatterene","Grimalin":"Impidimp","Fourbelin":"Morgrem","Angoliath":"Grimmsnarl","Ixon":"Obstagoon","Berserkatt":"Perrserker","Corayôme":"Cursola","Palarticho":"Sirfetch’d","M. Glaquette":"Mr. Rime","Tutétékri":"Runerigus","Crèmy":"Milcery","Charmilly":"Alcremie","Hexadron":"Falinks","Wattapik":"Pincurchin","Frissonille":"Snom","Beldeneige":"Frosmoth","Dolman":"Stonjourner","Bekaglaçon":"Eiscue","Wimessir":"Indeedee","Morpeko":"Morpeko","Charibari":"Cufant","Pachyradjah":"Copperajah","Galvagon":"Dracozolt","Galvagla":"Arctozolt","Hydragon":"Dracovish","Hydragla":"Arctovish","Duralugon":"Duraludon","Fantyrm":"Dreepy","Dispareptil":"Drakloak","Lanssorien":"Dragapult","Zacian":"Zacian","Zamazenta":"Zamazenta","Éthernatos":"Eternatus","Wushours":"Kubfu","Shifours":"Urshifu","Zarude":"Zarude","Regieleki":"Regieleki","Regidrago":"Regidrago","Blizzeval":"Glastrier","Spectreval":"Spectrier","Sylveroy":"Calyrex"}
data_en={'Bulbasaur': 'Bulbizarre', 'Ivysaur': 'Herbizarre', 'Venusaur': 'Florizarre', 'Charmander': 'Salamèche', 'Charmeleon': 'Reptincel', 'Charizard': 'Dracaufeu', 'Squirtle': 'Carapuce', 'Wartortle': 'Carabaffe', 'Blastoise': 'Tortank', 'Caterpie': 'Chenipan', 'Metapod': 'Chrysacier', 'Butterfree': 'Papilusion', 'Weedle': 'Aspicot', 'Kakuna': 'Coconfort', 'Beedrill': 'Dardargnan', 'Pidgey': 'Roucool', 'Pidgeotto': 'Roucoups', 'Pidgeot': 'Roucarnage', 'Rattata': 'Rattata', 'Raticate': 'Rattatac', 'Spearow': 'Piafabec', 'Fearow': 'Rapasdepic', 'Ekans': 'Abo', 'Arbok': 'Arbok', 'Pikachu': 'Pikachu', 'Raichu': 'Raichu', 'Sandshrew': 'Sabelette', 'Sandslash': 'Sablaireau', 'Nidoran♀': 'Nidoran♀', 'Nidorina': 'Nidorina', 'Nidoqueen': 'Nidoqueen', 'Nidoran♂': 'Nidoran♂', 'Nidorino': 'Nidorino', 'Nidoking': 'Nidoking', 'Clefairy': 'Mélofée', 'Clefable': 'Mélodelfe', 'Vulpix': 'Goupix', 'Ninetales': 'Feunard', 'Jigglypuff': 'Rondoudou', 'Wigglytuff': 'Grodoudou', 'Zubat': 'Nosferapti', 'Golbat': 'Nosferalto', 'Oddish': 'Mystherbe', 'Gloom': 'Ortide', 'Vileplume': 'Rafflesia', 'Paras': 'Paras', 'Parasect': 'Parasect', 'Venonat': 'Mimitoss', 'Venomoth': 'Aéromite', 'Diglett': 'Taupiqueur', 'Dugtrio': 'Triopikeur', 'Meowth': 'Miaouss', 'Persian': 'Persian', 'Psyduck': 'Psykokwak', 'Golduck': 'Akwakwak', 'Mankey': 'Férosinge', 'Primeape': 'Colossinge', 'Growlithe': 'Caninos', 'Arcanine': 'Arcanin', 'Poliwag': 'Ptitard', 'Poliwhirl': 'Têtarte', 'Poliwrath': 'Tartard', 'Abra': 'Abra', 'Kadabra': 'Kadabra', 'Alakazam': 'Alakazam', 'Machop': 'Machoc', 'Machoke': 'Machopeur', 'Machamp': 'Mackogneur', 'Bellsprout': 'Chétiflor', 'Weepinbell': 'Boustiflor', 'Victreebel': 'Empiflor', 'Tentacool': 'Tentacool', 'Tentacruel': 'Tentacruel', 'Geodude': 'Racaillou', 'Graveler': 'Gravalanch', 'Golem': 'Grolem', 'Ponyta': 'Ponyta', 'Rapidash': 'Galopa', 'Slowpoke': 'Ramoloss', 'Slowbro': 'Flagadoss', 'Magnemite': 'Magnéti', 'Magneton': 'Magnéton', 'Farfetch’d': 'Canarticho', 'Doduo': 'Doduo', 'Dodrio': 'Dodrio', 'Seel': 'Otaria', 'Dewgong': 'Lamantine', 'Grimer': 'Tadmorv', 'Muk': 'Grotadmorv', 'Shellder': 'Kokiyas', 'Cloyster': 'Crustabri', 'Gastly': 'Fantominus', 'Haunter': 'Spectrum', 'Gengar': 'Ectoplasma', 'Onix': 'Onix', 'Drowzee': 'Soporifik', 'Hypno': 'Hypnomade', 'Krabby': 'Krabby', 'Kingler': 'Krabboss', 'Voltorb': 'Voltorbe', 'Electrode': 'Électrode', 'Exeggcute': 'Noeunoeuf', 'Exeggutor': 'Noadkoko', 'Cubone': 'Osselait', 'Marowak': 'Ossatueur', 'Hitmonlee': 'Kicklee', 'Hitmonchan': 'Tygnon', 'Lickitung': 'Excelangue', 'Koffing': 'Smogo', 'Weezing': 'Smogogo', 'Rhyhorn': 'Rhinocorne', 'Rhydon': 'Rhinoféros', 'Chansey': 'Leveinard', 'Tangela': 'Saquedeneu', 'Kangaskhan': 'Kangourex', 'Horsea': 'Hypotrempe', 'Seadra': 'Hypocéan', 'Goldeen': 'Poissirène', 'Seaking': 'Poissoroy', 'Staryu': 'Stari', 'Starmie': 'Staross', 'Mr. Mime': 'M. Mime', 'Scyther': 'Insécateur', 'Jynx': 'Lippoutou', 'Electabuzz': 'Élektek', 'Magmar': 'Magmar', 'Pinsir': 'Scarabrute', 'Tauros': 'Tauros', 'Magikarp': 'Magicarpe', 'Gyarados': 'Léviator', 'Lapras': 'Lokhlass', 'Ditto': 'Métamorph', 'Eevee': 'Évoli', 'Vaporeon': 'Aquali', 'Jolteon': 'Voltali', 'Flareon': 'Pyroli', 'Porygon': 'Porygon', 'Omanyte': 'Amonita', 'Omastar': 'Amonistar', 'Kabuto': 'Kabuto', 'Kabutops': 'Kabutops', 'Aerodactyl': 'Ptéra', 'Snorlax': 'Ronflex', 'Articuno': 'Artikodin', 'Zapdos': 'Électhor', 'Moltres': 'Sulfura', 'Dratini': 'Minidraco', 'Dragonair': 'Draco', 'Dragonite': 'Dracolosse', 'Mewtwo': 'Mewtwo', 'Mew': 'Mew', 'Chikorita': 'Germignon', 'Bayleef': 'Macronium', 'Meganium': 'Méganium', 'Cyndaquil': 'Héricendre', 'Quilava': 'Feurisson', 'Typhlosion': 'Typhlosion', 'Totodile': 'Kaiminus', 'Croconaw': 'Crocrodil', 'Feraligatr': 'Aligatueur', 'Sentret': 'Fouinette', 'Furret': 'Fouinar', 'Hoothoot': 'Hoothoot', 'Noctowl': 'Noarfang', 'Ledyba': 'Coxy', 'Ledian': 'Coxyclaque', 'Spinarak': 'Mimigal', 'Ariados': 'Migalos', 'Crobat': 'Nostenfer', 'Chinchou': 'Loupio', 'Lanturn': 'Lanturn', 'Pichu': 'Pichu', 'Cleffa': 'Mélo', 'Igglybuff': 'Toudoudou', 'Togepi': 'Togepi', 'Togetic': 'Togetic', 'Natu': 'Natu', 'Xatu': 'Xatu', 'Mareep': 'Wattouat', 'Flaaffy': 'Lainergie', 'Ampharos': 'Pharamp', 'Bellossom': 'Joliflor', 'Marill': 'Marill', 'Azumarill': 'Azumarill', 'Sudowoodo': 'Simularbre', 'Politoed': 'Tarpaud', 'Hoppip': 'Granivol', 'Skiploom': 'Floravol', 'Jumpluff': 'Cotovol', 'Aipom': 'Capumain', 'Sunkern': 'Tournegrin', 'Sunflora': 'Héliatronc', 'Yanma': 'Yanma', 'Wooper': 'Axoloto', 'Quagsire': 'Maraiste', 'Espeon': 'Mentali', 'Umbreon': 'Noctali', 'Murkrow': 'Cornèbre', 'Slowking': 'Roigada', 'Misdreavus': 'Feuforêve', 'Unown': 'Zarbi', 'Wobbuffet': 'Qulbutoké', 'Girafarig': 'Girafarig', 'Pineco': 'Pomdepik', 'Forretress': 'Foretress', 'Dunsparce': 'Insolourdo', 'Gligar': 'Scorplane', 'Steelix': 'Steelix', 'Snubbull': 'Snubbull', 'Granbull': 'Granbull', 'Qwilfish': 'Qwilfish', 'Scizor': 'Cizayox', 'Shuckle': 'Caratroc', 'Heracross': 'Scarhino', 'Sneasel': 'Farfuret', 'Teddiursa': 'Teddiursa', 'Ursaring': 'Ursaring', 'Slugma': 'Limagma', 'Magcargo': 'Volcaropod', 'Swinub': 'Marcacrin', 'Piloswine': 'Cochignon', 'Corsola': 'Corayon', 'Remoraid': 'Rémoraid', 'Octillery': 'Octillery', 'Delibird': 'Cadoizo', 'Mantine': 'Démanta', 'Skarmory': 'Airmure', 'Houndour': 'Malosse', 'Houndoom': 'Démolosse', 'Kingdra': 'Hyporoi', 'Phanpy': 'Phanpy', 'Donphan': 'Donphan', 'Porygon2': 'Porygon2', 'Stantler': 'Cerfrousse', 'Smeargle': 'Queulorior', 'Tyrogue': 'Debugant', 'Hitmontop': 'Kapoera', 'Smoochum': 'Lippouti', 'Elekid': 'Élekid', 'Magby': 'Magby', 'Miltank': 'Écrémeuh', 'Blissey': 'Leuphorie', 'Raikou': 'Raikou', 'Entei': 'Entei', 'Suicune': 'Suicune', 'Larvitar': 'Embrylex', 'Pupitar': 'Ymphect', 'Tyranitar': 'Tyranocif', 'Lugia': 'Lugia', 'Ho-Oh': 'Ho-Oh', 'Celebi': 'Celebi', 'Treecko': 'Arcko', 'Grovyle': 'Massko', 'Sceptile': 'Jungko', 'Torchic': 'Poussifeu', 'Combusken': 'Galifeu', 'Blaziken': 'Braségali', 'Mudkip': 'Gobou', 'Marshtomp': 'Flobio', 'Swampert': 'Laggron', 'Poochyena': 'Medhyèna', 'Mightyena': 'Grahyèna', 'Zigzagoon': 'Zigzaton', 'Linoone': 'Linéon', 'Wurmple': 'Chenipotte', 'Silcoon': 'Armulys', 'Beautifly': 'Charmillon', 'Cascoon': 'Blindalys', 'Dustox': 'Papinox', 'Lotad': 'Nénupiot', 'Lombre': 'Lombre', 'Ludicolo': 'Ludicolo', 'Seedot': 'Grainipiot', 'Nuzleaf': 'Pifeuil', 'Shiftry': 'Tengalice', 'Taillow': 'Nirondelle', 'Swellow': 'Hélédelle', 'Wingull': 'Goélise', 'Pelipper': 'Bekipan', 'Ralts': 'Tarsal', 'Kirlia': 'Kirlia', 'Gardevoir': 'Gardevoir', 'Surskit': 'Arakdo', 'Masquerain': 'Maskadra', 'Shroomish': 'Balignon', 'Breloom': 'Chapignon', 'Slakoth': 'Parecool', 'Vigoroth': 'Vigoroth', 'Slaking': 'Monaflèmit', 'Nincada': 'Ningale', 'Ninjask': 'Ninjask', 'Shedinja': 'Munja', 'Whismur': 'Chuchmur', 'Loudred': 'Ramboum', 'Exploud': 'Brouhabam', 'Makuhita': 'Makuhita', 'Hariyama': 'Hariyama', 'Azurill': 'Azurill', 'Nosepass': 'Tarinor', 'Skitty': 'Skitty', 'Delcatty': 'Delcatty', 'Sableye': 'Ténéfix', 'Mawile': 'Mysdibule', 'Aron': 'Galekid', 'Lairon': 'Galegon', 'Aggron': 'Galeking', 'Meditite': 'Méditikka', 'Medicham': 'Charmina', 'Electrike': 'Dynavolt', 'Manectric': 'Élecsprint', 'Plusle': 'Posipi', 'Minun': 'Négapi', 'Volbeat': 'Muciole', 'Illumise': 'Lumivole', 'Roselia': 'Rosélia', 'Gulpin': 'Gloupti', 'Swalot': 'Avaltout', 'Carvanha': 'Carvanha', 'Sharpedo': 'Sharpedo', 'Wailmer': 'Wailmer', 'Wailord': 'Wailord', 'Numel': 'Chamallot', 'Camerupt': 'Camérupt', 'Torkoal': 'Chartor', 'Spoink': 'Spoink', 'Grumpig': 'Groret', 'Spinda': 'Spinda', 'Trapinch': 'Kraknoix', 'Vibrava': 'Vibraninf', 'Flygon': 'Libégon', 'Cacnea': 'Cacnea', 'Cacturne': 'Cacturne', 'Swablu': 'Tylton', 'Altaria': 'Altaria', 'Zangoose': 'Mangriff', 'Seviper': 'Séviper', 'Lunatone': 'Séléroc', 'Solrock': 'Solaroc', 'Barboach': 'Barloche', 'Whiscash': 'Barbicha', 'Corphish': 'Écrapince', 'Crawdaunt': 'Colhomard', 'Baltoy': 'Balbuto', 'Claydol': 'Kaorine', 'Lileep': 'Lilia', 'Cradily': 'Vacilys', 'Anorith': 'Anorith', 'Armaldo': 'Armaldo', 'Feebas': 'Barpau', 'Milotic': 'Milobellus', 'Castform': 'Morphéo', 'Kecleon': 'Kecleon', 'Shuppet': 'Polichombr', 'Banette': 'Branette', 'Duskull': 'Skelénox', 'Dusclops': 'Téraclope', 'Tropius': 'Tropius', 'Chimecho': 'Éoko', 'Absol': 'Absol', 'Wynaut': 'Okéoké', 'Snorunt': 'Stalgamin', 'Glalie': 'Oniglali', 'Spheal': 'Obalie', 'Sealeo': 'Phogleur', 'Walrein': 'Kaimorse', 'Clamperl': 'Coquiperl', 'Huntail': 'Serpang', 'Gorebyss': 'Rosabyss', 'Relicanth': 'Relicanth', 'Luvdisc': 'Lovdisc', 'Bagon': 'Draby', 'Shelgon': 'Drackhaus', 'Salamence': 'Drattak', 'Beldum': 'Terhal', 'Metang': 'Métang', 'Metagross': 'Métalosse', 'Regirock': 'Regirock', 'Regice': 'Regice', 'Registeel': 'Registeel', 'Latias': 'Latias', 'Latios': 'Latios', 'Kyogre': 'Kyogre', 'Groudon': 'Groudon', 'Rayquaza': 'Rayquaza', 'Jirachi': 'Jirachi', 'Deoxys': 'Deoxys', 'Turtwig': 'Tortipouss', 'Grotle': 'Boskara', 'Torterra': 'Torterra', 'Chimchar': 'Ouisticram', 'Monferno': 'Chimpenfeu', 'Infernape': 'Simiabraz', 'Piplup': 'Tiplouf', 'Prinplup': 'Prinplouf', 'Empoleon': 'Pingoléon', 'Starly': 'Étourmi', 'Staravia': 'Étourvol', 'Staraptor': 'Étouraptor', 'Bidoof': 'Keunotor', 'Bibarel': 'Castorno', 'Kricketot': 'Crikzik', 'Kricketune': 'Mélokrik', 'Shinx': 'Lixy', 'Luxio': 'Luxio', 'Luxray': 'Luxray', 'Budew': 'Rozbouton', 'Roserade': 'Roserade', 'Cranidos': 'Kranidos', 'Rampardos': 'Charkos', 'Shieldon': 'Dinoclier', 'Bastiodon': 'Bastiodon', 'Burmy': 'Cheniti', 'Wormadam': 'Cheniselle', 'Mothim': 'Papilord', 'Combee': 'Apitrini', 'Vespiquen': 'Apireine', 'Pachirisu': 'Pachirisu', 'Buizel': 'Mustébouée', 'Floatzel': 'Mustéflott', 'Cherubi': 'Ceribou', 'Cherrim': 'Ceriflor', 'Shellos': 'Sancoki', 'Gastrodon': 'Tritosor', 'Ambipom': 'Capidextre', 'Drifloon': 'Baudrive', 'Drifblim': 'Grodrive', 'Buneary': 'Laporeille', 'Lopunny': 'Lockpin', 'Mismagius': 'Magirêve', 'Honchkrow': 'Corboss', 'Glameow': 'Chaglam', 'Purugly': 'Chaffreux', 'Chingling': 'Korillon', 'Stunky': 'Moufouette', 'Skuntank': 'Moufflair', 'Bronzor': 'Archéomire', 'Bronzong': 'Archéodong', 'Bonsly': 'Manzaï', 'Mime Jr.': 'Mime Jr.', 'Happiny': 'Ptiravi', 'Chatot': 'Pijako', 'Spiritomb': 'Spiritomb', 'Gible': 'Griknot', 'Gabite': 'Carmache', 'Garchomp': 'Carchacrok', 'Munchlax': 'Goinfrex', 'Riolu': 'Riolu', 'Lucario': 'Lucario', 'Hippopotas': 'Hippopotas', 'Hippowdon': 'Hippodocus', 'Skorupi': 'Rapion', 'Drapion': 'Drascore', 'Croagunk': 'Cradopaud', 'Toxicroak': 'Coatox', 'Carnivine': 'Vortente', 'Finneon': 'Écayon', 'Lumineon': 'Luminéon', 'Mantyke': 'Babimanta', 'Snover': 'Blizzi', 'Abomasnow': 'Blizzaroi', 'Weavile': 'Dimoret', 'Magnezone': 'Magnézone', 'Lickilicky': 'Coudlangue', 'Rhyperior': 'Rhinastoc', 'Tangrowth': 'Bouldeneu', 'Electivire': 'Élekable', 'Magmortar': 'Maganon', 'Togekiss': 'Togekiss', 'Yanmega': 'Yanmega', 'Leafeon': 'Phyllali', 'Glaceon': 'Givrali', 'Gliscor': 'Scorvol', 'Mamoswine': 'Mammochon', 'Porygon-Z': 'Porygon-Z', 'Gallade': 'Gallame', 'Probopass': 'Tarinorme', 'Dusknoir': 'Noctunoir', 'Froslass': 'Momartik', 'Rotom': 'Motisma', 'Uxie': 'Créhelf', 'Mesprit': 'Créfollet', 'Azelf': 'Créfadet', 'Dialga': 'Dialga', 'Palkia': 'Palkia', 'Heatran': 'Heatran', 'Regigigas': 'Regigigas', 'Giratina': 'Giratina', 'Cresselia': 'Cresselia', 'Phione': 'Phione', 'Manaphy': 'Manaphy', 'Darkrai': 'Darkrai', 'Shaymin': 'Shaymin', 'Arceus': 'Arceus', 'Victini': 'Victini', 'Snivy': 'Vipélierre', 'Servine': 'Lianaja', 'Serperior': 'Majaspic', 'Tepig': 'Gruikui', 'Pignite': 'Grotichon', 'Emboar': 'Roitiflam', 'Oshawott': 'Moustillon', 'Dewott': 'Mateloutre', 'Samurott': 'Clamiral', 'Patrat': 'Ratentif', 'Watchog': 'Miradar', 'Lillipup': 'Ponchiot', 'Herdier': 'Ponchien', 'Stoutland': 'Mastouffe', 'Purrloin': 'Chacripan', 'Liepard': 'Léopardus', 'Pansage': 'Feuillajou', 'Simisage': 'Feuiloutan', 'Pansear': 'Flamajou', 'Simisear': 'Flamoutan', 'Panpour': 'Flotajou', 'Simipour': 'Flotoutan', 'Munna': 'Munna', 'Musharna': 'Mushana', 'Pidove': 'Poichigeon', 'Tranquill': 'Colombeau', 'Unfezant': 'Déflaisan', 'Blitzle': 'Zébibron', 'Zebstrika': 'Zéblitz', 'Roggenrola': 'Nodulithe', 'Boldore': 'Géolithe', 'Gigalith': 'Gigalithe', 'Woobat': 'Chovsourir', 'Swoobat': 'Rhinolove', 'Drilbur': 'Rototaupe', 'Excadrill': 'Minotaupe', 'Audino': 'Nanméouïe', 'Timburr': 'Charpenti', 'Gurdurr': 'Ouvrifier', 'Conkeldurr': 'Bétochef', 'Tympole': 'Tritonde', 'Palpitoad': 'Batracné', 'Seismitoad': 'Crapustule', 'Throh': 'Judokrak', 'Sawk': 'Karaclée', 'Sewaddle': 'Larveyette', 'Swadloon': 'Couverdure', 'Leavanny': 'Manternel', 'Venipede': 'Venipatte', 'Whirlipede': 'Scobolide', 'Scolipede': 'Brutapode', 'Cottonee': 'Doudouvet', 'Whimsicott': 'Farfaduvet', 'Petilil': 'Chlorobule', 'Lilligant': 'Fragilady', 'Basculin': 'Bargantua', 'Sandile': 'Mascaïman', 'Krokorok': 'Escroco', 'Krookodile': 'Crocorible', 'Darumaka': 'Darumarond', 'Darmanitan': 'Darumacho', 'Maractus': 'Maracachi', 'Dwebble': 'Crabicoque', 'Crustle': 'Crabaraque', 'Scraggy': 'Baggiguane', 'Scrafty': 'Baggaïd', 'Sigilyph': 'Cryptéro', 'Yamask': 'Tutafeh', 'Cofagrigus': 'Tutankafer', 'Tirtouga': 'Carapagos', 'Carracosta': 'Mégapagos', 'Archen': 'Arkéapti', 'Archeops': 'Aéroptéryx', 'Trubbish': 'Miamiasme', 'Garbodor': 'Miasmax', 'Zorua': 'Zorua', 'Zoroark': 'Zoroark', 'Minccino': 'Chinchidou', 'Cinccino': 'Pashmilla', 'Gothita': 'Scrutella', 'Gothorita': 'Mesmérella', 'Gothitelle': 'Sidérella', 'Solosis': 'Nucléos', 'Duosion': 'Méios', 'Reuniclus': 'Symbios', 'Ducklett': 'Couaneton', 'Swanna': 'Lakmécygne', 'Vanillite': 'Sorbébé', 'Vanillish': 'Sorboul', 'Vanilluxe': 'Sorbouboul', 'Deerling': 'Vivaldaim', 'Sawsbuck': 'Haydaim', 'Emolga': 'Emolga', 'Karrablast': 'Carabing', 'Escavalier': 'Lançargot', 'Foongus': 'Trompignon', 'Amoonguss': 'Gaulet', 'Frillish': 'Viskuse', 'Jellicent': 'Moyade', 'Alomomola': 'Mamanbo', 'Joltik': 'Statitik', 'Galvantula': 'Mygavolt', 'Ferroseed': 'Grindur', 'Ferrothorn': 'Noacier', 'Klink': 'Tic', 'Klang': 'Clic', 'Klinklang': 'Cliticlic', 'Tynamo': 'Anchwatt', 'Eelektrik': 'Lampéroie', 'Eelektross': 'Ohmassacre', 'Elgyem': 'Lewsor', 'Beheeyem': 'Neitram', 'Litwick': 'Funécire', 'Lampent': 'Mélancolux', 'Chandelure': 'Lugulabre', 'Axew': 'Coupenotte', 'Fraxure': 'Incisache', 'Haxorus': 'Tranchodon', 'Cubchoo': 'Polarhume', 'Beartic': 'Polagriffe', 'Cryogonal': 'Hexagel', 'Shelmet': 'Escargaume', 'Accelgor': 'Limaspeed', 'Stunfisk': 'Limonde', 'Mienfoo': 'Kungfouine', 'Mienshao': 'Shaofouine', 'Druddigon': 'Drakkarmin', 'Golett': 'Gringolem', 'Golurk': 'Golemastoc', 'Pawniard': 'Scalpion', 'Bisharp': 'Scalproie', 'Bouffalant': 'Frison', 'Rufflet': 'Furaiglon', 'Braviary': 'Gueriaigle', 'Vullaby': 'Vostourno', 'Mandibuzz': 'Vaututrice', 'Heatmor': 'Aflamanoir', 'Durant': 'Fermite', 'Deino': 'Solochi', 'Zweilous': 'Diamat', 'Hydreigon': 'Trioxhydre', 'Larvesta': 'Pyronille', 'Volcarona': 'Pyrax', 'Cobalion': 'Cobaltium', 'Terrakion': 'Terrakium', 'Virizion': 'Viridium', 'Tornadus': 'Boréas', 'Thundurus': 'Fulguris', 'Reshiram': 'Reshiram', 'Zekrom': 'Zekrom', 'Landorus': 'Démétéros', 'Kyurem': 'Kyurem', 'Keldeo': 'Keldeo', 'Meloetta': 'Meloetta', 'Genesect': 'Genesect', 'Chespin': 'Marisson', 'Quilladin': 'Boguérisse', 'Chesnaught': 'Blindépique', 'Fennekin': 'Feunnec', 'Braixen': 'Roussil', 'Delphox': 'Goupelin', 'Froakie': 'Grenousse', 'Frogadier': 'Croâporal', 'Greninja': 'Amphinobi', 'Bunnelby': 'Sapereau', 'Diggersby': 'Excavarenne', 'Fletchling': 'Passerouge', 'Fletchinder': 'Braisillon', 'Talonflame': 'Flambusard', 'Scatterbug': 'Lépidonille', 'Spewpa': 'Pérégrain', 'Vivillon': 'Prismillon', 'Litleo': 'Hélionceau', 'Pyroar': 'Némélios', 'Flabébé': 'Flabébé', 'Floette': 'Floette', 'Florges': 'Florges', 'Skiddo': 'Cabriolaine', 'Gogoat': 'Chevroum', 'Pancham': 'Pandespiègle', 'Pangoro': 'Pandarbare', 'Furfrou': 'Couafarel', 'Espurr': 'Psystigri', 'Meowstic': 'Mistigrix', 'Honedge': 'Monorpale', 'Doublade': 'Dimoclès', 'Aegislash': 'Exagide', 'Spritzee': 'Fluvetin', 'Aromatisse': 'Cocotine', 'Swirlix': 'Sucroquin', 'Slurpuff': 'Cupcanaille', 'Inkay': 'Sepiatop', 'Malamar': 'Sepiatroce', 'Binacle': 'Opermine', 'Barbaracle': 'Golgopathe', 'Skrelp': 'Venalgue', 'Dragalge': 'Kravarech', 'Clauncher': 'Flingouste', 'Clawitzer': 'Gamblast', 'Helioptile': 'Galvaran', 'Heliolisk': 'Iguolta', 'Tyrunt': 'Ptyranidur', 'Tyrantrum': 'Rexillius', 'Amaura': 'Amagara', 'Aurorus': 'Dragmara', 'Sylveon': 'Nymphali', 'Hawlucha': 'Brutalibré', 'Dedenne': 'Dedenne', 'Carbink': 'Strassie', 'Goomy': 'Mucuscule', 'Sliggoo': 'Colimucus', 'Goodra': 'Muplodocus', 'Klefki': 'Trousselin', 'Phantump': 'Brocélôme', 'Trevenant': 'Desséliande', 'Pumpkaboo': 'Pitrouille', 'Gourgeist': 'Banshitrouye', 'Bergmite': 'Grelaçon', 'Avalugg': 'Séracrawl', 'Noibat': 'Sonistrelle', 'Noivern': 'Bruyverne', 'Xerneas': 'Xerneas', 'Yveltal': 'Yveltal', 'Zygarde': 'Zygarde', 'Diancie': 'Diancie', 'Hoopa': 'Hoopa', 'Volcanion': 'Volcanion', 'Rowlet': 'Brindibou', 'Dartrix': 'Efflèche', 'Decidueye': 'Archéduc', 'Litten': 'Flamiaou', 'Torracat': 'Matoufeu', 'Incineroar': 'Félinferno', 'Popplio': 'Otaquin', 'Brionne': 'Otarlette', 'Primarina': 'Oratoria', 'Pikipek': 'Picassaut', 'Trumbeak': 'Piclairon', 'Toucannon': 'Bazoucan', 'Yungoos': 'Manglouton', 'Gumshoos': 'Argouste', 'Grubbin': 'Larvibule', 'Charjabug': 'Chrysapile', 'Vikavolt': 'Lucanon', 'Crabrawler': 'Crabagarre', 'Crabominable': 'Crabominable', 'Oricorio': 'Plumeline', 'Cutiefly': 'Bombydou', 'Ribombee': 'Rubombelle', 'Rockruff': 'Rocabot', 'Lycanroc': 'Lougaroc', 'Wishiwashi': 'Froussardine', 'Mareanie': 'Vorastérie', 'Toxapex': 'Prédastérie', 'Mudbray': 'Tiboudet', 'Mudsdale': 'Bourrinos', 'Dewpider': 'Araqua', 'Araquanid': 'Tarenbulle', 'Fomantis': 'Mimantis', 'Lurantis': 'Floramantis', 'Morelull': 'Spododo', 'Shiinotic': 'Lampignon', 'Salandit': 'Tritox', 'Salazzle': 'Malamandre', 'Stufful': 'Nounourson', 'Bewear': 'Chelours', 'Bounsweet': 'Croquine', 'Steenee': 'Candine', 'Tsareena': 'Sucreine', 'Comfey': 'Guérilande', 'Oranguru': 'Gouroutan', 'Passimian': 'Quartermac', 'Wimpod': 'Sovkipou', 'Golisopod': 'Sarmuraï', 'Sandygast': 'Bacabouh', 'Palossand': 'Trépassable', 'Pyukumuku': 'Concombaffe', 'Type: Null': 'Type:0', 'Silvally': 'Silvallié', 'Minior': 'Météno', 'Komala': 'Dodoala', 'Turtonator': 'Boumata', 'Togedemaru': 'Togedemaru', 'Mimikyu': 'Mimiqui', 'Bruxish': 'Denticrisse', 'Drampa': 'Draïeul', 'Dhelmise': 'Sinistrail', 'Jangmo-o': 'Bébécaille', 'Hakamo-o': 'Écaïd', 'Kommo-o': 'Ékaïser', 'Tapu Koko': 'Tokorico', 'Tapu Lele': 'Tokopiyon', 'Tapu Bulu': 'Tokotoro', 'Tapu Fini': 'Tokopisco', 'Cosmog': 'Cosmog', 'Cosmoem': 'Cosmovum', 'Solgaleo': 'Solgaleo', 'Lunala': 'Lunala', 'Nihilego': 'Zéroïd', 'Buzzwole': 'Mouscoto', 'Pheromosa': 'Cancrelove', 'Xurkitree': 'Câblifère', 'Celesteela': 'Bamboiselle', 'Kartana': 'Katagami', 'Guzzlord': 'Engloutyran', 'Necrozma': 'Necrozma', 'Magearna': 'Magearna', 'Marshadow': 'Marshadow', 'Poipole': 'Vémini', 'Naganadel': 'Mandrillon', 'Stakataka': 'Ama-Ama', 'Blacephalon': 'Pierroteknik', 'Zeraora': 'Zeraora', 'Meltan': 'Meltan', 'Melmetal': 'Melmetal', 'Grookey': 'Ouistempo', 'Thwackey': 'Badabouin', 'Rillaboom': 'Gorythmic', 'Scorbunny': 'Flambino', 'Raboot': 'Lapyro', 'Cinderace': 'Pyrobut', 'Sobble': 'Larméléon', 'Drizzile': 'Arrozard', 'Inteleon': 'Lézargus', 'Skwovet': 'Rongourmand', 'Greedent': 'Rongrigou', 'Rookidee': 'Minisange', 'Corvisquire': 'Bleuseille', 'Corviknight': 'Corvaillus', 'Blipbug': 'Larvadar', 'Dottler': 'Coléodôme', 'Orbeetle': 'Astronelle', 'Nickit': 'Goupilou', 'Thievul': 'Roublenard', 'Gossifleur': 'Tournicoton', 'Eldegoss': 'Blancoton', 'Wooloo': 'Moumouton', 'Dubwool': 'Moumouflon', 'Chewtle': 'Khélocrok', 'Drednaw': 'Torgamord', 'Yamper': 'Voltoutou', 'Boltund': 'Fulgudog', 'Rolycoly': 'Charbi', 'Carkol': 'Wagomine', 'Coalossal': 'Monthracite', 'Applin': 'Verpom', 'Flapple': 'Pomdrapi', 'Appletun': 'Dratatin', 'Silicobra': 'Dunaja', 'Sandaconda': 'Dunaconda', 'Cramorant': 'Nigosier', 'Arrokuda': 'Embrochet', 'Barraskewda': 'Hastacuda', 'Toxel': 'Toxizap', 'Toxtricity': 'Salarsen', 'Sizzlipede': 'Grillepattes', 'Centiskorch': 'Scolocendre', 'Clobbopus': 'Poulpaf', 'Grapploct': 'Krakos', 'Sinistea': 'Théffroi', 'Polteageist': 'Polthégeist', 'Hatenna': 'Bibichut', 'Hattrem': 'Chapotus', 'Hatterene': 'Sorcilence', 'Impidimp': 'Grimalin', 'Morgrem': 'Fourbelin', 'Grimmsnarl': 'Angoliath', 'Obstagoon': 'Ixon', 'Perrserker': 'Berserkatt', 'Cursola': 'Corayôme', 'Sirfetch’d': 'Palarticho', 'Mr. Rime': 'M. Glaquette', 'Runerigus': 'Tutétékri', 'Milcery': 'Crèmy', 'Alcremie': 'Charmilly', 'Falinks': 'Hexadron', 'Pincurchin': 'Wattapik', 'Snom': 'Frissonille', 'Frosmoth': 'Beldeneige', 'Stonjourner': 'Dolman', 'Eiscue': 'Bekaglaçon', 'Indeedee': 'Wimessir', 'Morpeko': 'Morpeko', 'Cufant': 'Charibari', 'Copperajah': 'Pachyradjah', 'Dracozolt': 'Galvagon', 'Arctozolt': 'Galvagla', 'Dracovish': 'Hydragon', 'Arctovish': 'Hydragla', 'Duraludon': 'Duralugon', 'Dreepy': 'Fantyrm', 'Drakloak': 'Dispareptil', 'Dragapult': 'Lanssorien', 'Zacian': 'Zacian', 'Zamazenta': 'Zamazenta', 'Eternatus': 'Éthernatos', 'Kubfu': 'Wushours', 'Urshifu': 'Shifours', 'Zarude': 'Zarude', 'Regieleki': 'Regieleki', 'Regidrago': 'Regidrago', 'Glastrier': 'Blizzeval', 'Spectrier': 'Spectreval', 'Calyrex': 'Sylveroy'}